### ISSUE TITLE
XML parser raises IndexError if single quotes are used instead of double quotes

### ISSUE THREAD

**Issue by davemevans** [futzu/threefive#119]
When parsing the following XML, `IndexError: list index out of range` will be raised. This is because the XML parser assumes that attributes are wrapped in double quotes, whereas single quotes are also valid.

```
<SpliceInfoSection tier='0'>
<TimeSignal>
<SpliceTime ptsTime='4'/>
</TimeSignal>
</SpliceInfoSection>
```

One to address at a later date.

(Note that (un/)escaping would also need to handle the &apos; in this case)

**Comment by futzu** [comment]
Damn it Dave, you didn't tell me single quotes are legal, what else aren't you telling me!! :)

**Comment by futzu** [comment]
So then  no attribute can contain a single qoute inside it, correct?
```xml
<anode  this='don't' >
```

**Comment by futzu** [comment]
this will work.

we replace `='` with `="` and `' [space]` with `" [space]` 
```py3
.replace("='",'="' ).replace("' ",'" ')

```

**Comment by davemevans** [comment]
> So then no attribute can contain a single qoute inside it, correct?
> 
> ```
> <anode  this='don't' >
> ```

This scenario is supported by escaping the `'` in the attribute value to be `&apos;`.
That should be added to `escape` and `unescape` in xml.py.

**Comment by futzu** [comment]
I'm replacing single quotes around attributes with double quotes. I can't think of a single SCTE-35 value that contains single or double quotes or a contraction like" don't". We're good here.
