### ISSUE TITLE
Exception in XML encode

### ISSUE THREAD

**Issue by wabiloo** [futzu/threefive#123]
Hi there,

I've found a small issue with the new XML encoding functionality.

```
❯ threefive encode xml < timesignal_mpu.json
Traceback (most recent call last):
  File "/bin/threefive", line 298, in <module>
    chk_print_map()
  File "/bin/threefive", line 280, in chk_print_map
    v()
  File "/bin/threefive", line 153, in json_load
    print2(method())
           ^^^^^^^^
  File "threefive/cue.py", line 477, in xml
    sis = self._xml_mk_descriptor(sis)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "threefive/cue.py", line 462, in _xml_mk_descriptor
    sis.add_child(d.xml())
                  ^^^^^^^
  File "threefive/descriptors.py", line 500, in xml
    upid_node = the_upid.xml()
                ^^^^^^^^^^^^^^
  File "threefive/upids.py", line 57, in xml
    return Node("SegmentationUpid", attrs=ud_attrs, value=self.upid_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "threefive/xml.py", line 124, in __init__
    self.value = escape(self.value)
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/xml/sax/saxutils.py", line 27, in escape
    data = data.replace("&", "&amp;")
           ^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'replace'
```

This happens when there are segmentation descriptors with UPIDs.

Here's the content of the `timesignal_mpu.json` file:
```
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",
        "sap_details": "No Sap Type",
        "section_length": 49,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment": 0.0,
        "cw_index": "0x00",
        "tier": "0x0fff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 27,
        "crc": "0x29f39a71"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 44277.952944
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 25,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "segmentation_event_id": "0xdcf1",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": true,
            "segmentation_duration": 34.56,
            "segmentation_upid_type": 12,
            "segmentation_upid_type_name": "MPU",
            "segmentation_upid_length": 5,
            "segmentation_upid": {
                "format_identifier": "OVLY",
                "private_data": "0x31"
            },
            "segmentation_type_id": 34,
            "segment_num": 0,
            "segments_expected": 0
        }
    ]
}
```

In this case the self.value is the dict `{ "format_identifier": "OVLY", "private_data": "0x31"}` which - naturally - cannot be used as argument to `.replace()`

Note that the same happens with other examples taken from your documentation, such as the one on https://github.com/futzu/threefive/blob/master/examples/upid/multi_upid.py

**Comment by wabiloo** [comment]
I - obviously - have the same issue when trying in a Python script. 

```
    cue = threefive.Cue(
        "0xFC303100000000000000FFF00506FEED8683D5001B0219435545490000DCF17FFF00002F76000C054F564C593122000029F39A71"
    )
    cue.decode()

    x = cue.xml()
    print(x)
```

No such issue if I use binary (for obvious reasons)
```
    xb = cue.xml(binary=True)
    print(xb)
```

**Comment by futzu** [comment]
I'm on it.....

**Comment by futzu** [comment]
I see what the problem is now, that upid.value holds multiples values as a dictionary, I need to encode  the dict values so that it's a singular value, 
sorry I thought I had done that. I'll try to get it sorted out tonight.

**Comment by futzu** [comment]
Does this look right?

```xml
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="3985015765"/>
   </TimeSignal>
   <!-- Break Start -->
   <SegmentationDescriptor segmentationEventId="56561" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="34" segmentNum="0" segmentsExpected="0" segmentationDuration="3110400">
      <!-- UPID: MPU -->
      <SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary">b'OVLY1'</SegmentationUpid>
   </SegmentationDescriptor>
</SpliceInfoSection>
```

**Comment by futzu** [comment]
Probably should be hex instead of bytes though

**Comment by futzu** [comment]
```xml 
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="3985015765"/>
   </TimeSignal>
   <!-- Break Start -->
   <SegmentationDescriptor segmentationEventId="56561" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="34" segmentNum="0" segmentsExpected="0" segmentationDuration="3110400">
      <!-- UPID: MPU -->
      <SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary">4f564c5931</SegmentationUpid>
   </SegmentationDescriptor>
</SpliceInfoSection>

```

**Comment by futzu** [comment]
I am in the middle of doing a new build , but it may be a few days, until then here's a replacement for  threefive/upids.py
[upids.zip](https://github.com/user-attachments/files/17639318/upids.zip)

I tried to make you a tarball, but it wouldn't upload it.

**Comment by futzu** [comment]
[new_upids.zip](https://github.com/user-attachments/files/17639980/new_upids.zip)

**Comment by wabiloo** [comment]
Yep, that's sort of what I expect (possibly in capital letters, but not sure whether that's important - in the way it is in HLS)

For comparison, here's one I got from a client, for comparison:
```xml
<EventStream timescale="90000" schemeIdUri="urn:scte:scte35:2013:xml">
    <Event>
      <scte35:SpliceInfoSection protocolVersion="0" ptsAdjustment="166098840" tier="4095">
        <scte35:TimeSignal>
          <scte35:SpliceTime ptsTime="611948848"/>
        </scte35:TimeSignal>
        <scte35:SegmentationDescriptor segmentationEventId="417282" segmentationEventCancelIndicator="false" segmentationDuration="1350000">
          <scte35:SegmentationUpid segmentationTypeId="48" segmentNum="1" segmentsExpected="16" segmentationUpidType="0" segmentationUpidLength="0"/>
        </scte35:SegmentationDescriptor>
        <scte35:SegmentationDescriptor segmentationEventId="417535" segmentationEventCancelIndicator="false">
          <scte35:SegmentationUpid segmentationTypeId="2" segmentNum="0" segmentsExpected="0" segmentationUpidType="12" segmentationUpidLength="16">414446520133F10134B04F065E060220</scte35:SegmentationUpid>
        </scte35:SegmentationDescriptor>
        <scte35:SegmentationDescriptor segmentationEventId="417281" segmentationEventCancelIndicator="false">
          <scte35:SegmentationUpid segmentationTypeId="49" segmentNum="0" segmentsExpected="16" segmentationUpidType="0" segmentationUpidLength="0"/>
        </scte35:SegmentationDescriptor>
      </scte35:SpliceInfoSection>
    </Event>
  </EventStream>
  ```

**Comment by davemevans** [comment]
Spec states that, for MPU, a `formatIdentifier` attribute should be included `SegmentationUpid`, expressed as an int, rather than included in the element value, though it seems @wabiloo's client's injector does not do this either.

eg 
```
<SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary" formatIdentifier="1331055705">31</SegmentationUpid>
```

**Comment by wabiloo** [comment]
@davemevans the Spec (2023) seems to indicate that it's optional. Do you understand "Specify for MPU only" as being compulsory in the case where the UPID is MPU?
For me, I don't mind what's done, provided that the content of the <SegmentationUpid> is left untouched (ie. left to contain the format identifier)

**Comment by davemevans** [comment]
I do. The definition of optionality in the spec is poor (like most things relating to XML in the SCTE spec) - there's a bunch of attributes marked as optional which would make the XML nonsense if omitted.

I don't think it makes sense, or complies with the spec, to encode the format identifier in the value and also an attribute.

I don't really have a horse in this race - just interested in interoperability.

**Comment by futzu** [comment]
Sorry, I got a lot going on right now and couldn't remember which of the 14 specs I need to read to find the actual details for MPU.
You want format identifier as an int attribute, that's not a problem.

The spec said the upid value, the upid value is the format_identifer and the  private_data, which  is consistent with the handling of the most of the other Upids.

 I think it would say, private data for the xml value if it only wanted the private_data, **I don't know.**

**I don't care either way, just tell how you want it.**  

**The value is hex so upper case and lower case shouldn't matter.** 

@davemevans which SCTE spec  were you reading? I just looked at the SCTE-35 spec. I didn't have the strength to go through all 5  SCTE-214 specs and 67 and 223 .....etc.

I did a v2.4.90 pre release build  if y'all want to pip it up and try it.

**Comment by futzu** [comment]
What really pisses me off , is that there is not a single xml example in the SCTE-35 spec.

**Comment by futzu** [comment]
Here's the MPU stuff in the SCTE-35 spec. 
Post whatever you find related to MPU , let's figure this out. 
 
![image](https://github.com/user-attachments/assets/a8e7bdb4-4a1d-491e-b933-491fdeec0302)

**Comment by futzu** [comment]
@wabiloo , I know SuperDave is against using the scte35 namespace, what about you?
Everything I see uses it, so I'm wondering if we should.

**Comment by futzu** [comment]
On the Namespace

![image](https://github.com/user-attachments/assets/51eb8f1d-b468-46fc-a9a2-6ce5c6e2ad91)

**Comment by futzu** [comment]
![image](https://github.com/user-attachments/assets/30ba577f-1f21-4d14-bc1f-2caa97d157c5)


So we need the format_identifier as an int attribute, no problem there. 

I have a two hour meeting at two o'clock, y'all figure out what goes for the xml value itself, and I'll do a build tonight.
I'll add the format_identifier right now.

**Comment by futzu** [comment]
```xml
a@fu:~/build/SCTE35_threefive$ cat json.json |./threefive.py encode xml
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="3985015765"/>
   </TimeSignal>
   <!-- Break Start -->
   <SegmentationDescriptor segmentationEventId="56561" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="34" segmentNum="0" segmentsExpected="0">
      <!-- UPID: MPU -->
      <SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary" formatIdentifier="1331055705">4f564c59000000000049</SegmentationUpid>
   </SegmentationDescriptor>
</SpliceInfoSection>
```

**Comment by wabiloo** [comment]
OK, that one gives me a small issue... As per my example, my customers don't have the formatIdentifier as an attribute, and instead have it in the UPID payload. Which our solution extracts as is to send (for example) to the ad server...

I'm not sure I'm in agreement with @davemevans when he says that "_I don't think it makes sense, or complies with the spec, to encode the format identifier in the value and also an attribute._". 
For me the very fact that private_data's definition has "_The length is defined by the segmentation_upid_length, which includes the format_identifier field length_." seems to implicitly contradict that stance.

If we go the way you just showed and Dave asks for, would that also prevent parsing the (real-life) example I provided?  Or parsing then re-encoding the payload return something different from the input?

**Comment by wabiloo** [comment]
@futzu  on the namespace, I will respond in the Discussion rather than this ticket, to avoid confusing matters

**Comment by davemevans** [comment]
> For me the very fact that private_data's definition has "The length is defined by the segmentation_upid_length, which includes the format_identifier field length." seems to implicitly contradict that stance.

That definition is explicitly that is for the binary representation. To me it simply states that private_data length, N, is defined by `segmentation_upid_length - len(format_identifier)`. Regardless, it says nothing about the XML representation.

For reference, another real world example (output from scte35-go):
```
<SpliceInfoSection xmlns="http://www.scte.org/schemas/35" sapType="3" tier="4095">
	<EncryptedPacket xmlns="http://www.scte.org/schemas/35" encryptionAlgorithm="0" cwIndex="0"></EncryptedPacket>
	<TimeSignal xmlns="http://www.scte.org/schemas/35">
		<SpliceTime xmlns="http://www.scte.org/schemas/35" ptsTime="3985015765"></SpliceTime>
	</TimeSignal>
	<SegmentationDescriptor xmlns="http://www.scte.org/schemas/35" segmentationEventId="56561" segmentationDuration="3110400" segmentationTypeId="34">
		<SegmentationUpid xmlns="http://www.scte.org/schemas/35" segmentationUpidType="12" segmentationUpidFormat="base-64" formatIdentifier="1331055705">MQ==</SegmentationUpid>
	</SegmentationDescriptor>
</SpliceInfoSection>
```

At the end of the day, I don't have a current use case for MPU, so I'm not that bothered. I think the spec is fairly clear, but since there is an actual use case maybe it makes sense to satisfy that for now and worry about it when the next person comes along.

**Comment by futzu** [comment]
No offense, but **I do not consider  scte-35-go to be a valid reference**, I know some folks at SCTE, I'm going to hit them for a definitive answer.
@wabiloo , I did the format_identifer as an attribute, **but it's also included in the value.**

**Comment by futzu** [comment]
If either one of y'all do HLS, checkout the hls SCTE-35 parser I put in the threefive cli, 
it is pretty sweet.  run it against a master.m3u8 over the network . It does mpegts hls and for audio only streams, it even parses timestamps from id3 header tags. 

```js
threefive hls https://example.com/master.m3u8
```

**Comment by davemevans** [comment]
I don't think there is any valid reference for SCTE35 XML tbh, including threefive. I just included it as another real-world data point.

> I know some folks at SCTE, I'm going to hit them for a definitive answer.

This is the right approach :+1:

**Comment by futzu** [comment]
tsduck, if he does it, it probably correct. He's really the only other SCTE-35 I trust.

I'll ask SCTE, and we should really look at how the big guys like akamai and amazon do it.



"OK, that one gives me a small issue... As per my example, my customers don't have the formatIdentifier as an attribute, and instead have it in the UPID payload. Which our solution extracts as is to send (for example) to the ad server..."

**it's in the payload too**

I'm not trying to be a dick about it,  but y'all should be pushing folks to the  binary format, 
just for your own sanity. Look at how long we have been working on this, and still aren't sure. 

* This is from amazon, it doesn't match anything we're talking about, it look like they use binary representation for the value, I guess, and look at attributes, They have 0100, which I read as a 4 bit binary 4.

```xml
<Period start="PT346530.250S" id="123456" duration="PT61.561S">
  <EventStream timescale="90000" schemeIdUri="urn:scte:scte35:2013:xml">
    <Event duration="5310000">
      <scte35:SpliceInfoSection protocolVersion="0" ptsAdjustment="183003" tier="4095">
        <scte35:TimeSignal>
          <scte35:SpliceTime ptsTime="3442857000"/>
        </scte35:TimeSignal>
        <scte35:SegmentationDescriptor segmentationEventId="1234567" segmentationEventCancelIndicator="false" segmentationDuration="8100000" segmentationTypeId="52" segmentNum="0" segmentsExpected="0">
          <scte35:DeliveryRestrictions webDeliveryAllowedFlag="false" noRegionalBlackoutFlag="false" archiveAllowedFlag="false" deviceRestrictions="3"/>
          <scte35:SegmentationUpid segmentationUpidType="12" segmentationUpidLength="2">0100</scte35:SegmentationUpid>
        </scte35:SegmentationDescriptor>
      </scte35:SpliceInfoSection>
    </Event>

```

**Comment by futzu** [comment]
![image](https://github.com/user-attachments/assets/b23417e7-623c-4d8d-b6ef-f67a836abdae)

We are the first hit, if we don't know the answer, we need to make something up :)

**Comment by wabiloo** [comment]
> **it's in the payload too**

Sorry, I missed that then!

> I'm not trying to be a dick about it,  but y'all should be pushing folks to the  binary format, 

Yeah, but I have very little influence on what my I-am-a-big-operator-customers-do-you-know-who-I-am do, in particular when using junkware packagers designed in the early 2000s 

> * This is from amazon, it doesn't match anything we're talking about, it look like they use binary representation for the value, I guess, and look at attributes, They have 0100, which I read as a 4 bit binary 4.


For reference, my example at https://github.com/futzu/threefive/issues/123#issuecomment-2459528934 was from AWS MediaPackage - but I don't trust them to output something that's kosher either...

**Comment by futzu** [comment]
We have spent way too much time on this, 

Here's what I'm going to do for MPU,

*  **The entire UPID  meaning format_identifier and private_data will be the xml value**
*  **formatIdentifier will be an integer attribute**
*  **privateData will be an integer attribute** 

**That makes the most sense and gives the highest compatibility.**

When in doubt, I prefer too much to not enough. 


Can y'all both live with that?

**Comment by wabiloo** [comment]
Seems like a good compromise. And using hexbinary for the value by default (Ie. not allowing text or base64 options)?

**Comment by futzu** [comment]
I am assuming the hexbinary is a reference to the upid payload format, there are upid types that I specify as text if they are encoded as text, but for a complex upid like MPU , it seems the best way to do it. 
Here's what it looks like now.

**Actually privateData as an attribute has to be an int too. we can't use hex as an attribute.**


```xml
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="3985015765"/>
   </TimeSignal>
   <!-- Break Start -->
   <SegmentationDescriptor segmentationEventId="56561" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="34" segmentNum="0" segmentsExpected="0">
      <!-- UPID: MPU -->
      <SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary" formatIdentifier="1331055705" privateData="73">4f564c59000000000049</SegmentationUpid>
   </SegmentationDescriptor>
</SpliceInfoSection>
```

**Comment by davemevans** [comment]
Please don't add the `privateData` attribute - this isn't a valid attribute in the default namespace so validation against the schema will fail.

**Comment by futzu** [comment]
Here's what the spec says,
![image](https://github.com/user-attachments/assets/723fe1b8-f007-4a7c-9913-5b79fb3f9c7b)




I spent days making it work without length for you,  it won't validate against the schema anyway because the spec and schema are not in sync.
I appreciate your input, I really do, but since we don't know what right is,  I need to do what I think is best, because I have to deal with it.I have to handle the issues, I have to write the code and I have spent a lot of time on this, and I am ready to wrap this up.
 I have spent at 40 hours of my time on this. 
If you want something exactly how you need it, you can hire me and we can do it, 
but for this,I have to do what's best for the most people. 

I still can't figure out how to be compatible with amazon and they won't validate either. Compatibility trumps the spec every time.

**Comment by futzu** [comment]
> Please don't add the `privateData` attribute - this isn't a valid attribute in the default namespace so validation against the schema will fail.

@davemevans  This isn't even your issue man. Listen, obviously your company uses threefive, you're at least the third person I've encountered from your company.  I have given you a ton of my time, if you need more help, hire me. We'll do everything your way. 
 I got us this far, so I'm going to keep doing threefive my way.

**Comment by davemevans** [comment]
I have been participating in my own time, and for my own interest, because I thought it was a cool project I could get involved with in my spare time and hopefully lend some limited expertise to help build out useful functionality for the community.

Keep on doing what you're doing, it's appreciated.

**Comment by futzu** [comment]
@davemevans  I'm trying to figure out how to be compatible with everybody, I still have no idea what to do with amazon, I am baffled by their output. I'm hoping that the xml they have in the docs, is just something they put up, and just threw some values in to demonstrate what it look like or something. 
<br/>
The only way threefive can be compatible with most people is to stick some extra data in, I cannot come up another way to make it all work. I don't think too many folks are using the SpliceInfoSection format, and SCTE is no longer maintaining it, that's why it's such a pain in the ass.
<br/> 
I would love to be able to follow the spec to the letter, but if I do that, it won't work in the real world. 

the pts of 0.0 is another non-standard. That is done so that live streams using sidecar files can be injected with Cues on the fly with the PTS set to zero to  indicate to splice Immediate or to return early from an ad break, because  TimeSignal doesn't have a splice immediate flag.

**Comment by futzu** [comment]
@wabiloo @davemevans 
I added the scte-35 namespace as the default for xml. 
However, it can be disabled by  setting ns="" when you call cue.xml
If you set the name space when you call cue.xml() it will propagate to 
all the child nodes. So now Cue.xml accepts two optional args,  binary and ns
the defaults are Cue.xml(binary=False, ns="scte35")

Here I set it to "bob"   `cue.xml(ns='bob'`)`
```xml
<bob:SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <bob:TimeSignal>
      <bob:SpliceTime ptsTime="5400000"/>
   </bob:TimeSignal>
   <!-- Provider Placement Opportunity End -->
   <bob:SegmentationDescriptor segmentationEventId="1644168586" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="53" segmentNum="0" segmentsExpected="0">
      <!-- ADI -->
      <bob:SegmentationUpid segmentationUpidType="9" segmentationUpidFormat="text">SIGNAL:3-sQ4NgFT0OjPsG4WqUQow</bob:SegmentationUpid>
   </bob:SegmentationDescriptor>
</bob:SpliceInfoSection>

```

* then an empty string   `cue.xml(ns='')`
```xml
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="5400000"/>
   </TimeSignal>
   <!-- Provider Placement Opportunity End -->
   <SegmentationDescriptor segmentationEventId="1644168586" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="53" segmentNum="0" segmentsExpected="0">
      <!-- ADI -->
      <SegmentationUpid segmentationUpidType="9" segmentationUpidFormat="text">SIGNAL:3-sQ4NgFT0OjPsG4WqUQow</SegmentationUpid>
   </SegmentationDescriptor>
</SpliceInfoSection>

```

and this is the default   `cue.xml()`

```xml
<scte35:SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <scte35:TimeSignal>
      <scte35:SpliceTime ptsTime="5400000"/>
   </scte35:TimeSignal>
   <!-- Provider Placement Opportunity End -->
   <scte35:SegmentationDescriptor segmentationEventId="1644168586" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="53" segmentNum="0" segmentsExpected="0">
      <!-- ADI -->
      <scte35:SegmentationUpid segmentationUpidType="9" segmentationUpidFormat="text">SIGNAL:3-sQ4NgFT0OjPsG4WqUQow</scte35:SegmentationUpid>
   </scte35:SegmentationDescriptor>
</scte35:SpliceInfoSection>




```

**Comment by futzu** [comment]
If you notice segmentationUpidFormat="text", 
I added a method to the Upid class so we can 
specify format by UPID type .
```py3

    def _xml_format_attr(self):
        """
        _xml_format_attr sets segmentation_upid_format
        """
        if self.upid_type in [0x03, 0x07, 0x09, 0x0E]:
            return "text"
        return "hexbinary"
```
I also added a method to add extra vars when the UPID is a dictionary, 
this way it's all in the same place.

```py3

    def _extra_xml_attrs(self, ud):
        if "format_identifier" in self.upid_value:
            ud["format_identifier"] = int.from_bytes(
            self.upid_value["format_identifier"].encode(), byteorder="big"
            )
        if "private_data" in self.upid_value:
            ud["private_data"]=self.upid_value["private_data"]
        return ud
```

* xml only calls self._xml_format_attr()
```py3
   def xml(self, ns="scte35"):
        """
        xml return a upid xml node
        """
        ud_attrs = {
            "segmentation_upid_type": self.upid_type,
            "segmentation_upid_format": self._xml_format_attr(),       < ---- xml format
        }
        return Node("SegmentationUpid", attrs=ud_attrs, value=self.upid_value,ns=ns)
````
* complexml calls both new methods. complexml is only used on complex UPIDS that are dictionaries, like MPU, ATSC etc...
```py3

    def complexml(self, ns="scte35"):
        """
        complexml return a upid xml node for complex upids
        """
        ud_attrs = {
            "segmentation_upid_type": self.upid_type,
            "segmentation_upid_format": self._xml_format_attr(), <--- xml format attr
        }
        if isinstance(self.upid_value,dict):   
            ud_attrs = self._extra_xml_attrs(ud_attrs)   <--- add extra attrs if needed
        nbin = NBin()
        self.encode(nbin, self.upid_value)
        return Node("SegmentationUpid", attrs=ud_attrs, value=nbin.bites.hex(),ns=ns)

```

```



```

**Comment by futzu** [comment]
I've also made a new function called  rm_xmlattr
it takes two args an xml string and the name of the attr to remove, 


```py3
 from threefive.xml import rm_xmlattr
```
```xml
 exemel ="""<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
        <SpliceTime ptsTime="3985015765"/>
            </TimeSignal>
              <!-- Break Start -->
                  <SegmentationDescriptor segmentationEventId="56561" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="34" segmentNum="0" segmentsExpected="0">
                       <!-- UPID: MPU-->
                             <SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary" formatIdentifier="1331055705" privateData="73">4f564c5949</SegmentationUpid>
                               </SegmentationDescriptor>
                           </SpliceInfoSection>"""
```
```py3
>>>> print(rm_xmlattr(exemel,"privateData"))
```
```xml
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
         <SpliceTime ptsTime="3985015765"/>
            </TimeSignal>
               <!-- Break Start -->
                  <SegmentationDescriptor segmentationEventId="56561" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="true" segmentationTypeId="34" segmentNum="0" segmentsExpected="0">
                        <!-- UPID: MPU-->
                              <SegmentationUpid segmentationUpidType="12" segmentationUpidFormat="hexbinary" formatIdentifier="1331055705" >4f564c5949</SegmentationUpid>                                                        
                                 </SegmentationDescriptor>
                                 </SpliceInfoSection>

```
  No more privateData. 

I'll probably make some methods in the Node class to do this a bit cleaner.
