### ISSUE TITLE
Cannot serialise TimeSignal with pts 0.0 to XML

### ISSUE THREAD

**Issue by davemevans** [futzu/threefive#124]
The following sample incorrectly produces an empty `<TimeSignal>`:

```
>>> import threefive
>>> cue = threefive.Cue()
>>> cue.command = threefive.TimeSignal()
>>> cue.command.pts_time = 0.0
>>> cue.command.time_specified_flag = True
>>> cue.encode()
'/DAWAAAAAAAAAP/wBQb+AAAAAAAAcU5hWg=='
>>> cue.xml()
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal/>
</SpliceInfoSection>
```

It should be something like:

```
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="0"/>
   </TimeSignal>
</SpliceInfoSection>
```

Looks like a similar issue to #113.

I also note that an explicit call to `encode()` is required before `xml()`, otherwise serialisation fails completely due to what looks like something initialised to None. Is this expected?

**Comment by futzu** [comment]
No, it should not, that's exactly what it's supposed to do, fail.
It is intentional.

Yes, you are required to call encode when ever create an object.

**Comment by futzu** [comment]
Of course you have to encode, all you made was a TimeSignal, where do think the rest of it came from?

**Comment by davemevans** [comment]
Understood on the encode call, explicit encode was not required when calling xml when i last tested this in v2.4.79 so the behaviour seems to have changed. Make sense - thanks for clarifying.

pts_time 0 is valid so I'm not sure why it should fail to generate `<TimeSignal><SpliceTime ptsTime="0"/></TimeSignal>` but I will take your word for it.
