### ISSUE TITLE
Encoding and Inserting SCTE35 packets into MPEG-TS video

### ISSUE THREAD

**Issue by futzu** [futzu/threefive#15]
*  I'm about to start adding __**SCTE35 encoding methods.**__
    * I created the __bitn.NBin class__ to make __encoding data to  easy__.
    * __check this out:__
          * The first method ___parse_break__, is the __decoder using bitn.BitBin.__
        *   ___encode_break, the encoder using bitn.NBin__ follows the __same flow__ as the decoder method.
```js
    def _parse_break(self, bitbin):
        """
        SpliceInsert._parse_break(bitbin) is called
        if SpliceInsert.duration_flag is set
        """
        self.break_auto_return = bitbin.asflag(1)
        bitbin.forward(6)
        self.break_duration = bitbin.as90k(33)

    def _encode_break(self, nbin):
        """
        SpliceInsert._encode_break(nbin) is called
        if SpliceInsert.duration_flag is set
        """
        nbin.add_flag(self.break_auto_return)
        nbin.forward(6)
        nbin.add_90k(self.break_duration, 33)

    ```

**Comment by richard-vd** [comment]
I know a fair bit of PIDs and packets and can validate the output. I am however new at coding Python so bear with me.

**Comment by futzu** [comment]
If you can figure out what steps we need to:
*  Add a  SCTE-35 stream
*  Add MPEG-TS packets

I can help you with the code.

The encoding for the __splice info section__, and __the splice commands__ is __done__. 
The encoding for __Audio, Avail, DTMF, and Time descriptors__ is __done__.
 Only the __Segmentation Descriptors remain__, and I'm about to start on them now.

**Comment by futzu** [comment]
## threefive.Cue can now Encode and Decode itself for all Splice Commands and Descriptors. 
The currently supported __Segmentation Upid__ types:
-  [x] __0x02__  
-  [x] __0x03__  
- [x] __0x04__
-  [x] __0x05__
-  [x] __0x06__ 
- [x]  __0x07__  
- [x]  __0x08__ 
- [x]  __0x09__ 
- [x]    __0x0A__
- [x]  __0x0B__
- [x]   __0x0C__
- [x]   __0x0D__ 
- [x]  __0x0E__  
- [x]  __0x0F__ 



```
 Cue.bites --->>> b'\xfc0/\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\x05\x00\x00\x02\x96\x7f\xef\xff\xe1j\x1a\xb8~\x01LV \x00\x01\x00\x00\x00\n\x00\x08CUEI\x00\x00\x00\x00\x10\xfaM\x9e'

 Encoded   --->>> b'\xfc0/\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\x05\x00\x00\x02\x96\x7f\xef\xff\xe1j\x1a\xb8~\x01LV \x00\x01\x00\x00\x00\n\x00\x08CUEI\x00\x00\x00\x00\x10\xfaM\x9e'
```
