### ISSUE TITLE
multi packet PMT and PAT/PMT with adaptation field not working

### ISSUE THREAD

**Issue by richard-vd** [futzu/threefive#16]
Hi,

Current TS and section parsing code doesn't handle:

1. large PMT sections (>1 TS packet)
2. multiple table sections in a single TS packet (section starting at arbitrary position in TS payload)
3. TS packets with smaller payload (adaptation field stuffing)

I am working on it.

**Comment by futzu** [comment]
When you do the adaptive fields stuff, 
we will need these later for SCTE35 packet insertion 
splice_point_flag
splice_countdown.

and from the adaption extensions format
seamless splice flag .

**Comment by futzu** [comment]
Can you post some of the packets in question or a chunk of the video somewhere I can get to it??
I have a few servers, if you send me an email, a@so.slo.me, I'll make you a user and you can upload it there.

**Comment by richard-vd** [comment]
Example of a TS file containing situations 1. and 2.:
https://patchwork.ffmpeg.org/project/ffmpeg/patch/20180611074331.28844-1-ffmpeg@tmm1.net/

**Comment by futzu** [comment]
Cool. I'll check it out. 

We're close, take a look at 
https://github.com/futzu/SCTE35-threefive/blob/master/threefive/afc.py

**Comment by futzu** [comment]
Do you have a copy of the mpegts spec? 
I've been using the  2nd edition from 2000

**Comment by futzu** [comment]
https://github.com/futzu/SCTE35-threefive/discussions/19

**Comment by futzu** [comment]
I havent seen AFC in use on PMT packets, have you?
grab afc.py  and 
```
pypy3 afc.py video.ts | less
```
It spits out tons of info

**Comment by richard-vd** [comment]
My MPEG-2 TS spec is not newer than yours. I don't think we're missing much though.

**Comment by futzu** [comment]
It works now.
