### ISSUE TITLE
Issue with time signal SCTE-35

### ISSUE THREAD

**Issue by ffmv30** [futzu/threefive#34]
Hi,

The segmentation type id for time signal messages are not being converted correctly. 

For version 2.2.25: 
The segmentation_type_id incorrectly shows "segmentation_type_id": 109. 

For version 2.2.95: 
When using three5.show(), The descriptors are empty. 
When using three5.decode(), TypeError: cannot unpack non-iterable bool object. 

Example of the segmentation type id being properly converted: 
https://openidconnectweb.azurewebsites.net/Cue?cue=/DA7AAAAAtaWAAAABQb+t0XCpwAlAiNDVUVJ/////3+/ARRtc25iY19FUDAyNTA0MTMwMTIxOQEBAKAxzMk=

Sample cue in base64: 
/DA7AAAAAtaWAAAABQb+t0XCpwAlAiNDVUVJ/////3+/ARRtc25iY19FUDAyNTA0MTMwMTIxOQEBAKAxzMk=

**Comment by futzu** [comment]
> For version 2.2.25:
The segmentation_type_id incorrectly shows "segmentation_type_id": 109.

 **2.2.25 was 852 commits ago,  I would solve that one with pip :)**
```
pip3 install --upgrade threefive
```
---


> For version 2.2.95:
> When using three5.show(), The descriptors are empty.
> When using three5.decode(), TypeError: cannot unpack non-iterable bool object.As for 2.2.95


#####  According to the SCTE-35 specification, 

> Segmentation upid type 0x01 is deprecated you should be using upid type **0x0C**. 

![upid_table](https://user-images.githubusercontent.com/52701496/127578295-e03c8646-28d8-4f35-aba0-72fea0e987e7.png)

---



### What the site is doing is just passing you back ascii chars for the bytes.

### I'll put a fix in tonight to do the same thing.

 **Does this look better?**
```js
>>>> from threefive import Cue
>>>> cue = Cue('/DA7AAAAAtaWAAAABQb+t0XCpwAlAiNDVUVJ/////3+/ARRtc25iY19FUDAyNTA0MTMwMTIxOQEBAKAxzMk=')
>>>> cue.decode()
True
>>>> cue.show()
{
      "info_section": {
            "table_id": "0xfc",
            "section_syntax_indicator": false,
            "private": false,
            "sap_type": "0x3",
            "sap_details": "No Sap Type",
            "section_length": 59,
            "protocol_version": 0,
            "encrypted_packet": false,
            "encryption_algorithm": 0,
            "pts_adjustment": 2.066733,
            "cw_index": "0x0",
            "tier": "0x0",
            "splice_command_length": 5,
            "splice_command_type": 6,
            "descriptor_loop_length": 37
      },
      "command": {
            "calculated_length": 5,
            "name": "Time Signal",
            "time_specified_flag": true,
            "pts_time": 34166.537211
      },
      "descriptors": [
            {
                  "tag": 2,
                  "descriptor_length": 35,
                  "name": "Segmentation Descriptor",
                  "identifier": "CUEI",
                  "components": [],
                  "segmentation_event_id": "0xffffffff",
                  "segmentation_event_cancel_indicator": false,
                  "program_segmentation_flag": true,
                  "segmentation_duration_flag": false,
                  "delivery_not_restricted_flag": true,
                  "segmentation_message": "Content Identification",
                  "segmentation_upid_type": 1,
                  "segmentation_upid_type_name": "Deprecated",
                  "segmentation_upid_length": 20,
                  "segmentation_upid": "msnbc_EP025041301219",
                  "segmentation_type_id": 1,
                  "segment_num": 1,
                  "segments_expected": 0
            }
      ],
      "crc": "0xa031ccc9"
}
```

**Comment by ffmv30** [comment]
Yes this looks correct. The descriptors are exactly what was expected. Thanks for all your efforts!

**Comment by futzu** [comment]
**Cool.**
I'll make a package for pip version **2.2.97** as soon as I can. Most likely tonight.  

Heads up, 
That website includes  **sub_segment_num** and **sub_segment_expected**, which is incorrect.

![sub-segment](https://user-images.githubusercontent.com/52701496/127587505-a0152571-bba1-4720-b1f1-f9620bc20246.png)

**Comment by futzu** [comment]
> Try it and let me know if it works correctly for you. 

> _Adrian_

```sh
a@fumatica:~/threefive$ pypy3 -mpip install --upgrade threefive
Requirement already satisfied: threefive in /home/a/.local/lib/pypy3.7/site-packages (2.2.95)
Collecting threefive
  Downloading threefive-2.2.97-py3-none-any.whl (20 kB)
Installing collected packages: threefive
  Attempting uninstall: threefive
    Found existing installation: threefive 2.2.95
    Uninstalling threefive-2.2.95:
      Successfully uninstalled threefive-2.2.95
Successfully installed threefive-2.2.97
```

**Comment by ffmv30** [comment]
Works perflectly after the update. Will take note of the sub_segment issues on that site. 

Appreciate all the help, thanks again!
