### ISSUE TITLE
Decoder exception error - threefive v.2.2.99 

### ISSUE THREAD

**Issue by ffmv30** [futzu/threefive#36]
Hi,

Encountering an exception error when using the threefive.decode function. 

Sample base64 message: 
/DA4AAAAAAAAAP/wFAUACM+hf+//BEfkX34AUmNiAAAAAAATAAVTQVBTAQEKQ1VFSQCfMzIwKsHmwpY=

Command used:
>>>
threefive.decode('/DA4AAAAAAAAAP/wFAUACM+hf+//BEfkX34AUmNiAAAAAAATAAVTQVBTAQEKQ1VFSQCfMzIwKsHmwpY=')

**Error Message:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/threefive/decode.py", line 38, in _read_stuff
    with open(stuff, "rb") as tsdata:
FileNotFoundError: [Errno 2] No such file or directory: '/DA4AAAAAAAAAP/wFAUACM+hf+//BEfkX34AUmNiAAAAAAATAAVTQVBTAQEKQ1VFSQCfMzIwKsHmwpY='

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/threefive/decode.py", line 44, in _read_stuff
    with open(stuff, "rb") as tsdata:
FileNotFoundError: [Errno 2] No such file or directory: '/DA4AAAAAAAAAP/wFAUACM+hf+//BEfkX34AUmNiAAAAAAATAAVTQVBTAQEKQ1VFSQCfMzIwKsHmwpY='

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/threefive/decode.py", line 122, in decode
    return _read_stuff(stuff)
  File "/usr/local/lib/python3.9/site-packages/threefive/decode.py", line 48, in _read_stuff
    return _decode_and_show(stuff)
  File "/usr/local/lib/python3.9/site-packages/threefive/decode.py", line 20, in _decode_and_show
    if cue.decode():
  File "/usr/local/lib/python3.9/site-packages/threefive/cue.py", line 67, in decode
    after_dscrptrs = self._mk_descriptors(after_cmd)
  File "/usr/local/lib/python3.9/site-packages/threefive/cue.py", line 156, in _mk_descriptors
    self._descriptorloop(bites, dll)
  File "/usr/local/lib/python3.9/site-packages/threefive/cue.py", line 82, in _descriptorloop
    spliced = splice_descriptor(bites)
  File "/usr/local/lib/python3.9/site-packages/threefive/descriptors.py", line 247, in splice_descriptor
    spliced = descriptor_map[tag](bites)
  File "/usr/local/lib/python3.9/site-packages/threefive/descriptors.py", line 24, in __init__
    self.parse_id()
  File "/usr/local/lib/python3.9/site-packages/threefive/descriptors.py", line 44, in parse_id
    raise Exception('Identifier Is Not "CUEI"')
Exception: Identifier Is Not "CUEI"

 
**The show function will properly convert the message but decode is throwing this error on the base64 messages.** 

**Commands Used:**
cue=threefive.Cue('/DA4AAAAAAAAAP/wFAUACM+hf+//BEfkX34AUmNiAAAAAAATAAVTQVBTAQEKQ1VFSQCfMzIwKsHmwpY=')

>>> cue.decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/threefive/cue.py", line 67, in decode
    after_dscrptrs = self._mk_descriptors(after_cmd)
  File "/usr/local/lib/python3.9/site-packages/threefive/cue.py", line 156, in _mk_descriptors
    self._descriptorloop(bites, dll)
  File "/usr/local/lib/python3.9/site-packages/threefive/cue.py", line 82, in _descriptorloop
    spliced = splice_descriptor(bites)
  File "/usr/local/lib/python3.9/site-packages/threefive/descriptors.py", line 247, in splice_descriptor
    spliced = descriptor_map[tag](bites)
  File "/usr/local/lib/python3.9/site-packages/threefive/descriptors.py", line 24, in __init__
    self.parse_id()
  File "/usr/local/lib/python3.9/site-packages/threefive/descriptors.py", line 44, in parse_id
    raise Exception('Identifier Is Not "CUEI"')
Exception: Identifier Is Not "CUEI"

>>> cue.show()
{
      "info_section": {
            "table_id": "0xfc",
            "section_syntax_indicator": false,
            "private": false,
            "sap_type": "0x3",
            "sap_details": "No Sap Type",
            "section_length": 56,
            "protocol_version": 0,
            "encrypted_packet": false,
            "encryption_algorithm": 0,
            "pts_adjustment": 0.0,
            "cw_index": "0x0",
            "tier": "0xfff",
            "splice_command_length": 20,
            "splice_command_type": 5,
            "descriptor_loop_length": 19
      },
      "command": {
            "calculated_length": 20,
            "name": "Splice Insert",
            "time_specified_flag": true,
            "pts_time": 48519.8631,
            "break_auto_return": false,
            "break_duration": 59.993267,
            "splice_event_id": 577441,
            "splice_event_cancel_indicator": false,
            "out_of_network_indicator": true,
            "program_splice_flag": true,
            "duration_flag": true,
            "splice_immediate_flag": false,
            "unique_program_id": 0,
            "avail_num": 0,
            "avail_expected": 0
      },
      "descriptors": []
}

Appears to be working here using this online tool: https://comcast.github.io/scte35-js/

Can you please take a look at this issue?
Do let me know if you need more information.

**Comment by futzu** [comment]
#### According to the spec.....

![Screenshot_2021-09-03_01-15-46](https://user-images.githubusercontent.com/52701496/131993265-f2a3ad74-e00a-4578-bbf4-f1071f27f65a.png)


> However, I don't see the harm in __not__ throwing an error.
```python3
>>>> from threefive import version
>>>> version()
'2.3.01'
>>>> 


>>>> from threefive import decode
>>>> decode('/DA4AAAAAAAAAP/wFAUACM+hf+//BEfkX34AUmNiAAAAAAATAAVTQVBTAQEKQ1VFSQCfMzIwKsHmwpY=')
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x3",
        "sap_details": "No Sap Type",
        "section_length": 56,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment": 0.0,
        "cw_index": "0x0",
        "tier": "0xfff",
        "splice_command_length": 20,
        "splice_command_type": 5,
        "descriptor_loop_length": 19,
        "crc": "0xc1e6c296"
    },
    "command": {
        "calculated_length": 20,
        "name": "Splice Insert",
        "time_specified_flag": true,
        "pts_time": 48519.8631,
        "break_auto_return": false,
        "break_duration": 59.993267,
        "splice_event_id": 577441,
        "splice_event_cancel_indicator": false,
        "out_of_network_indicator": true,
        "program_splice_flag": true,
        "duration_flag": true,
        "splice_immediate_flag": false,
        "unique_program_id": 0,
        "avail_num": 0,
        "avail_expected": 0
    },
    "descriptors": [
        {
            "tag": 0,
            "descriptor_length": 5,
            "name": "Avail Descriptor",
            "identifier": "SAPS",
            "provider_avail_id": 16845379
        },
        {
            "tag": 1,
            "descriptor_length": 10,
            "name": "DTMF Descriptor",
            "identifier": "CUEI",
            "preroll": 0,
            "dtmf_chars": [
                "3",
                "2",
                "0",
                "*"
            ]
        }
    ]
}
True
>>>> 
```
>
> give me a couple hours and I will push a pip package.

**Comment by futzu** [comment]
Try this and let me know what happens
https://pypi.org/project/threefive/2.3.1/

**Comment by ffmv30** [comment]
Thanks for the update! Works fine now and no longer getting that error.

**Comment by futzu** [comment]
Cool man. 
You describe issues well, 
makes it much easier to figure out.
If there is a feature you need, let me know.
