### ISSUE TITLE
hasp.py error in decoding hls manifest

### ISSUE THREAD

**Issue by ozrocozroc** [futzu/threefive#37]
the issue I am experiencing when testing hasp.py with my project is that when I try to it to decode scte35 messages I am getting the following error:
======error log start
Traceback (most recent call last):
  File "/home/dhuang/scte35-threefive/examples/hls/hasp.py", line 177, in <module>
    HASP(arg).decode()
  File "/home/dhuang/scte35-threefive/examples/hls/hasp.py", line 150, in decode
    hold = stanza.decode()
  File "/home/dhuang/scte35-threefive/examples/hls/hasp.py", line 96, in decode
    self._aes_start(line)
  File "/home/dhuang/scte35-threefive/examples/hls/hasp.py", line 38, in _aes_start
    self._aes_decrypt()
  File "/home/dhuang/scte35-threefive/examples/hls/hasp.py", line 49, in _aes_decrypt
    with urllib.request.urlopen(self.segment) as infile:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
======error log end
the url & command I am using as a test:
`python3 $HOME/scte35-threefive/examples/hls/hasp.py https://9now-livestreams.akamaized.net/hls/live/2007330/ch9-syd/master1.m3u8`

interestingly, when I download the manifest(m3u8)  manually and using hlsparse.py and it decoded without any issue.
I am hoping someone can assist me in pointing me in the right direction.
Sorry for being new to this and please let me know if you require additional info.

Thanks,
ozrocozroc

**Comment by futzu** [comment]
Could you paste the manifest here?
It is only available in Oz.
The hasp.py example was targeted to a particular manifest, I left a lot of stuff out.  It was mostly to show the AES decrypt.
Hasp.py decrypts the first segment in the manifest to determine the start time of the segment from the PCR timestamp. The hlsparse.py script does not. hlsparse.py only reads the manifest.

It looks like hasp.py is unable to download the first segment from the error message. 

Here's what I need from you.

1. If you would post the manifest here so I can see it.
2.  Run this command 
` ffprobe https://9now-livestreams.akamaized.net/hls/live/2007330/ch9-syd/master1.m3u8  2>&1 >> ffprobe.out`

**Comment by futzu** [comment]
Don't worry, this won't take long to figure out.

**Comment by ozrocozroc** [comment]
Thanks for getting back to me.
1. Please see attached manifest, renamed to "9syd_master1.m3u8.txt" (to comply with github upload)
[9syd_master1.m3u8.txt](https://github.com/futzu/scte35-threefive/files/7334751/9syd_master1.m3u8.txt)

2. attached filename (ffprobe.out.txt)
[ffprobe.out.txt](https://github.com/futzu/scte35-threefive/files/7334750/ffprobe.out.txt)

**Comment by futzu** [comment]
Try this one.

[haspfix.py.gz](https://github.com/futzu/scte35-threefive/files/7337876/haspfix.py.gz)

**Comment by futzu** [comment]
This one is a bit better.
[hasp3.py.gz](https://github.com/futzu/scte35-threefive/files/7340436/hasp3.py.gz)
I still need to fix a couple things with it, let me know your thoughts.

**Comment by ozrocozroc** [comment]
initial testing suggests it's working now!  Thank you!
I can also see that you've also gone extra steps to fix non-absolute URI.
Which fixed my other problem as well 👍🏽 
Thank you very much for the speedy response.

**Comment by futzu** [comment]
Cool. 
Here's an update.
[hasp4.py.gz](https://github.com/futzu/scte35-threefive/files/7342946/hasp4.py.gz)

**Comment by ozrocozroc** [comment]
Thanks again.

**Comment by futzu** [comment]
My pleasure, I appreciate the feedback. 
https://github.com/futzu/scte35-threefive/blob/master/examples/hls/hasp.py
Is the latest greatest version. 
Ill do a pip release this week with all the updates in it.
