### ISSUE TITLE
Incorrect pts time

### ISSUE THREAD

**Issue by AudioDan** [futzu/threefive#39]
We have an 86MB, 9 to 10 minute video snippet where for the first of 2 SCTE messages, in version 2.2.99 the pcr shows 87726.9313 and the pts shows 87726.952711.  But when moving the 2.3.01 or 2.3.03, the pcr shows 87726.9313 but the pts shows 87.381333.  When monitoring a live video stream over 10 hours we may see approximately 8 out of 61 Scte35 messages have this exact 87.381333 value instead of the correct value.  PCR looks correct in all cases and the same video stream sample under 2.2.99 looks correct as well.  So we think there may have been a bug introduced.  I probably should not make the video snippet available publicly as it has copyright material in it, but if there is a way we could share it with you privately I would be happy to do so.   Thoughts?

Additional question, in the xml output does pts_time already have the pts_adjustment factored in or not?  We had assumed not and so were adding it in our calculations, but looking at the code it looks like it might be in which case we would be double adding it.

**Comment by futzu** [comment]
Let me look into it tonight
 
The pts_adjustment is added to pts_time,  but I am thinking maybe it should not be, because it is kind of confusing. What do you think?

**Comment by futzu** [comment]
Try this script and see how it does with 2.3.03.

``` python3 streamfu.py video.ts```

[streamfu.py.gz](https://github.com/futzu/scte35-threefive/files/7438780/streamfu.py.gz)

**Comment by AudioDan** [comment]
>> The pts_adjustment is added to pts_time, but I am thinking maybe it should not be, because it is kind of confusing. What do you think?

It seems to me that parameters that by name directly refer to the SCTE35 specification should only express the specification  So pts_time should not have the pts_adjustment in it.  That does not mean we can't have an additional non-spec field (for example pts_adjusted_time) if we think having that calculation automatically done is useful.  Having said that I have concerns about changing it as well.  Has pts_time always included pts_adjustment or is that a newer change?  One of the things I would like to see us get a little more careful about in this project is calling out breaking changes via documentation and/or major semver release numbers.  And in my mind this would be a breaking change for anyone using the resulting json in an application.  As more and more people come to rely on this project, that becomes more of a pain point.  So we may want to think whether this is better left alone and more clearly documented so as to not break consuming applications, or if it is better/cleaner to make the change and call it out clearly.  I am good with either decision, just let me know and I will adjust accordingly.

Python is a not a language I write in much. But I am thinking about trying to write some functional or unit tests towards this project.  I am envisioning a set of video files and/or binary blobs where on each checkin, the resulting json would get intelligently compared against known good json.  Adding fields and/or event sections should not cause breakages, but that kind of test could both catch bugs and call out places where we are making breaking changes to the json.  Perhaps even a json schema.

For example, between 2.5.95 and 2.5.99 we moved the pts and pcr fields into a packet_data section.  I actually really like this.  It makes a lot of sense.  But it also potentially breaks anyone's code that is expecting the previous structure.  So should it be a major semver release?  I mostly bring this up because I have come to expect needing to tweak my code when I do upgrades of this project regardless of whether it is a major semver release.

That's not to criticize.  This is a phenomenal project and I love how fast it is moving forward.   You are doing really awesome work here.

**Comment by AudioDan** [comment]
Yep that seems to fix it.  
Using the streamfu.py for the offending break I get:
    "packet_data": {
        "pid": "0x1f4",
        "program": 1,
        "pcr": 87726.9313,
        "pts": 87726.952711
    }

Using 2.3.01 I get:
   "packet_data": {
        "pid": "0x1f4",
        "program": 1,
        "pcr": 87726.9313,
        "pts": 87.381333
    }

So is this something you can get into a new build?  It would be hugely helpful to testing we are doing at the moment.  I was going to downgrade to 2.5.99 but I think that we moved to 2.3.01 for a different video stream because of a fix you did on the splice descriptor identifiers exception.  Thanks again for your help on this.

**Comment by futzu** [comment]
Dan, 
let me be clear, I really appreciate your input, and your directness, it is a big help.
The PTS  parsing has actually never been correct, I was using `if pkt[6] & 1:` when it should have been `if pkt[11] & 128:`, 
in 2.2.99 the correct PTS values were a side effect of the order of the returns in the _parse function. I only caught it last night because you opened this issue and I went back through the spec..

What made it difficult to diagnose was that a lot of streams have PCR and PTS values that are very different. Like with ffmpeg, if you don't use `-copyts` the PCR stays the same but PTS is started at 0. 

The testing is something I have been thinking about often. I am open to ideas. 
I need more real world samples, and nobody wants to give them to me.

The JSON schema is set. I am happy with it now.
 I don't like to break stuff, but I was concerned the pts from the packet might be confused as SCTE35 data. 

I agree with you on the pts adjustment. It should NOT be included. 

I was going to do release yesterday, but I saw your issue and I wanted to resolve it first.
I will do a release tonight, and make sure changes are noted. 

Release 2.3.05 will include:

the PTS parsing fix I sent you last night.

the pts_adjustment will NOT be added in from now on.

**Comment by AudioDan** [comment]
Perfect.  I really appreciate how responsive you are on this project.  

Let me think about the testing.  Like I said my python is weak, but I have been looking for an open source project to help with and this might be fun if I can find some time.  It might be something dead simple to start with like a script that takes a folder as an argument and expects to find a bunch of video files and text files in the folder.  It runs each file through the decode script and compares the results against the similarly named text file.   Then users could build their own libraries to run the tests against as well as whatever you have.  That is a little inflexible if we want to add a field or something later but it is a starting place, and we could add intelligence with real json parsing and analysis later.  Additionally we could use something like tstools in an docker container to play the files.  That was actually my thought for our own testing was building a library in an s3 bucket with expected results.

I understand the problem with getting content.  When I first started tinkering with your project I could only find 2 or 3 files to test with.  And now that we are trying it against real video streams, we have the rights to consume the streams and do things based on the SCTE35 breaks provided, but we are not the actual content creators so making it available to a third party requires jumping through some hoops.  But let me think on that a bit as well.

Thanks again for the great product.

**Comment by futzu** [comment]
I could use some help, and I can help you with python syntax. We should talk about it. 

Here's the new release details. 

https://github.com/futzu/scte35-threefive/releases/tag/v2.3.05

**Comment by AudioDan** [comment]
If you wouldn't mind, leave this open until Wednesday and then we can close it.  Initial testing looks good but we won't be able to put it up against our actual test streams until sometime early next week.  Just to double check pts_time, pts_adjustment, and pts are all being reported in seconds with the 90k conversion already handled - correct?  So if one wanted to know in milliseconds the difference between when we receive a splice insert and when it should fire it would be 
((pts_time - pts) + pts_adjustment) * 1000 
correct?

FYI - I woke up at 2:30 AM this morning and couldn't get back to sleep for over an hour because I was thinking about ways to set up and automate tests for this project.  So I will try to find some time to fork and play with that and then start something in discussions on it.  We will see how much time I can find, but I definitely have some ideas.

Thanks again for the fast turn around,

**Comment by AudioDan** [comment]
So the sample file and stream I was originally working with is working now I think, but it seems to be breaking a different sample that was working in 2.3.01.  On that sample, when streaming to 2.3.05 using tstools/tsplay I get:

Traceback (most recent call last):"
  File \"/usr/bin/sai/scte35/scte35_listener.py\", line 110, in <module>"
    read_stream(sock,show_null)"
  File \"/usr/bin/sai/scte35/scte35_listener.py\", line 52, in read_stream"
    ts.decode()"
  File \"/usr/bin/sai/scte35/scte35_listener.py\", line 44, in decode"
    cue = self._parse(pkt)"
  File \"/usr/bin/_pypy/pypy/site-packages/threefive-2.3.5-py3.7.egg/threefive/stream.py\", line 324, in _parse"
    return self._parse_pcr(pkt, pid)"
  File \"/usr/bin/_pypy/pypy/site-packages/threefive-2.3.5-py3.7.egg/threefive/stream.py\", line 298, in _parse_pcr"
    prgm = self._pid_prgm[pid]"
KeyError: 8190"

The crash happens almost immediately.

That sample was working under 2.3.01 and I just confirmed that by rolling back and forth.

If it useful, here is data that tsplay spits out about the stream when I start to play it:

Connecting to 192.168.1.23 via UDP on port 5000
Writing    to 192.168.1.23 via UDP
Input appears to be Transport Stream
Using 'exact' TS packet timing (by looking-ahead to the next PCR)
Circular buffer size 1024 (+1)
Transmitting (up to) 7 TS packets (1316 bytes) per network packet/circular buffer item
Requested data rate is 20 Mbps (2500000 bytes/second)
Maximum number of packets to send with no wait: 40
Number of microseconds to wait thereafter: 1000
PCR mechanism 'primed' with time for 10 circular buffer items
Multiply PCRs by 1
Parent will wait 4ms for buffer to unfill
Child will wait 1ms for buffer to unempty
Circular buffer filling...
Packet 2847 is PAT
Program list:
    Program 1 -> PID 0020 (32)
Packet 5728 starts PMT with PID 0020
  Program 1, version 0, PCR PID 1ffe (8190)
     Program info (6 bytes): 05 04 43 55 45 49
     Registration CUEI
  Program streams:
    PID 0134 ( 308) -> Stream type 1b ( 27) H.264/14496-10 video (MPEG-4/AVC)
        ES info (6 bytes): 28 04 4d 40 20 3f
        Reserved (4 bytes): 4d 40 20 3f
    PID 0100 ( 256) -> Stream type 03 (  3) 11172-3 audio (MPEG-1)
    PID 0101 ( 257) -> Stream type 03 (  3) 11172-3 audio (MPEG-1)
    PID 0102 ( 258) -> Stream type 86 (134) User private
Taking timing information from PID 0x1ffe
Circular buffer filled - starting to send data
Transferred 20116135 TS packets in total
Started  output at Sun Oct 31 14:30:42 2021
Finished output at Sun Oct 31 14:55:53 2021
Elapsed time 1511.0s

**Comment by AudioDan** [comment]
A little more info if useful.  I have 7 files all exported ts files created by doing a wireshark capture on some live udp streams from different sources we are working with.  We use the Dump Mpeg TS packets tool (https://wiki.wireshark.org/mpeg_dump.lua) to dump from a wireshark cpature to a an mpegts file.  I created a little test script to just decode the files: 

import threefive 
import sys

if __name__ == '__main__':
    args = sys.argv[1:]
    for arg in args:
        print(f"Next File: {arg}")
        threefive.decode(arg)

All 7 files work under 2.3.01 albeit with some of them showing the incorrect pts stamp we have been working to correct in this thread.  Under 2.3.05 all but one file works (the same one throwing the errors above when being streamed).  That file dumps out immediately.

**Comment by AudioDan** [comment]
I dug into this a bit and found where it was crashing and then looked into the changes in that function between 2.3.01 and 2.3.05.  Reverting 3 lines of code in the _parse_pcr method seems to fix it for my test files while still gaining the pts fixes in 2.3.05.  I issued a pull request for the change.

Note: My forked version also has a branch as I cherry-picked the fix onto a branch of 2.3.05.  There were changes in Master and I was not sure if they were to be considered stable yet so I branched 2.3.05 and added the patch there as well for my own use.  You do not need to pull that branch and I will clean it up later in my fork.  It is likely I will start a testing branch on my fork as well and then get back to you once I have something useful.  Probably going to start by trying to get a CI file created.

Thanks,

**Comment by futzu** [comment]
I believe we have resolved the issues. 
* The PTS issue was resolved with 2.3.05
    * The PTS parsing has actually never been correct, I was using `if pkt[6] & 1:` when it should have been `if pkt[11] & 128:`
* The PCR issue was resolved with 2.3.07
    * The PCR issue was due to the PCR PID of the Program not being a stream in the Program.I was unaware this was possible, or allowed. I adjusted the code to add the pcr_pid  to the Stream. _pid_prgm  map
   ` self._pid_prgm[pcr_pid] = program_number`  to allow for a PCR_PID that is not a stream in the Program. 

@AudioDan  Close this if we are good, or tell me what isn't working.
*

**Comment by AudioDan** [comment]
Yep. Sorry the week got away from me but it is all looking great.  closing now.

**Comment by futzu** [comment]
Cool man. Thanks for all your help.

**Comment by futzu** [comment]
@audioDan
could you check the timestamps returned  by the code in the repo ( version 2.3.10 )
with the video for this issue? I'm not seeing any issues, but I would like a second opinion.

**Comment by AudioDan** [comment]
Today was a bit nuts with meetings but I will give it a whirl in the morning and hit you back.

**Comment by futzu** [comment]
Cool. Thanks man.

**Comment by AudioDan** [comment]
My morning ending up being nuts too, but got into this a little bit ago.  So far everything looks good.  Note that there is no tag for 2.3.10 yet but I pulled the commit that you marked as being 2.3.10.  I have run a simple decode test against all of my sample files and compared the results to what we had with 2.3.07 and they are identical.  Next I have updated my vm and am streaming those same files in real time to it using tsplay and so far it is all looking good as well though it will be a few hours before I finish playing all of them.  I started with the problematic files so I am pretty sure it is good.   One question did you want this tested only against 2.3.10 commit or also against latest master?

**Comment by futzu** [comment]
The latest master please. I have no idea how to add tags. :)

**Comment by futzu** [comment]
This may be a little easier to handle. 

gunzip this
[timestamps.py.gz](https://github.com/futzu/scte35-threefive/files/7645914/timestamps.py.gz)
you can do something like
```
pypy3 timestamps.py videos_dir/*.ts
```
It will give short output
```sh
Video: ../mpegts/ooo.ts
Splice Insert PCR:38104.5658 PTS:None
Splice Insert PCR:38104.5658 PTS:None
Video: ../mpegts/scte35.ts
Splice Null PCR:89669.407689 PTS:89669.377522
Splice Null PCR:89671.421244 PTS:89671.393522
Splice Null PCR:89673.4703 PTS:89673.409522
Splice Null PCR:89675.518144 PTS:89675.569522
Splice Null PCR:89677.5672 PTS:89677.585522
Splice Null PCR:89679.581356 PTS:89679.601522
Splice Null PCR:89681.631 PTS:89681.617522

```
you can ```pypy3  timestamps.py *.ts >>  out.file``` too.

**Comment by futzu** [comment]
This is how I have been checking it. 

```sh
gunzip timestamps.py.gz 

cp timestamps.py ~/threefive

cd ~/threefive

pypy3 timestamps.py ../mpegts/*.ts >> master.out

cd ../

cp threefive/timestamps.py .

pypy3 timestamps.py mpegts/*.ts >> pip-threefive.out

diff pip-threefive.out  threefive/master.out >> diff.out

```
post diff.out here.

**Comment by AudioDan** [comment]
So I did pip install threefive==2.3.07.  Then ran your script on each video capturing the output to a file.  Then from within the repository directory I did pip install . to install master version which showed 2.3.10 though I assume it is actually 2.3.10 plus the changes since that are in master.  Then I ran your script again on each video capturing the output to a file.  The diff shows no difference between the two files.  That's what we want and expect - correct?

**Comment by AudioDan** [comment]
Here is a combination of the output of 5 files.  Note the a file has its breaks expressed in segmentation descriptors
[all.txt](https://github.com/futzu/scte35-threefive/files/7646283/all.txt)
.

**Comment by futzu** [comment]
Yes, that is exactly what we wanted. 
I implemented faster packet parsing and I wanted to make sure there were not any errors. 

Cool man. Thank you so much.

**Comment by AudioDan** [comment]
Awesome.  Not a problem.
