### ISSUE TITLE
syntax error in Python 3.4

### ISSUE THREAD

**Issue by richard-vd** [futzu/threefive#4]
```
# pip3 install threefive
Downloading/unpacking threefive
  Downloading threefive-2.1.79-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): bitn>=0.0.27 in /usr/local/lib/python3.4/dist-packages (from threefive)
Installing collected packages: threefive
*** Error compiling '/tmp/pip-build-a1bjun2e/threefive/threefive/segmentation.py'...
  File "/tmp/pip-build-a1bjun2e/threefive/threefive/segmentation.py", line 137
    return f'{upid_map[upid_type][0]}:{upid_id}'
                                               ^
SyntaxError: invalid syntax

Successfully installed threefive
Cleaning up...
```

**Comment by vladdoster** [comment]
@richard-vd

This is due to the use of [f strings](https://www.python.org/dev/peps/pep-0498/). 

To remedy the error, you'll need to use Python >= 3.6.

**Comment by futzu** [comment]
Vlad is correct, I love  the f strings. Is there a reason you need to use python3.4?

**Comment by futzu** [comment]
I apologize, I should have made the python requirement more clear. 

I believe there are only three lines that have f strings.

`
$ grep -n "f'" threefive/*.py

threefive/segmentation.py:137:                return f'{upid_map[upid_type][0]}:{upid_id}'
threefive/segmentation.py:176:        return f'{pre}{middle[2:6]}{post}'
threefive/segmentation.py:199:        return f'10.{pre}/{post[2:6]}-{post[6:10]}-{post[10:14]}-{post[14:18]}-T'        
'                                                                             `

**Comment by futzu** [comment]
Python recently dropped support for python3.5, 
and Vlad updated setup.py to reflect the 3.6 requirement.
I'm closing this issue.

**Comment by richard-vd** [comment]
Thanks for clarifying the required Python version in setup and documentation!
