### ISSUE TITLE
Consider making crcmod an optional dependency

### ISSUE THREAD

**Issue by bbayles** [futzu/threefive#46]
Commit 1feffa62f54c83884e1de38d51eeebc6b3d2871e allowed users without `crcmod` installed to use the bits of`Cue` functionality that don't require it.

However, [setup.py](https://github.com/futzu/scte35-threefive/blob/d9f4896e377d6d6c2da5cc8aa88d0ab0a3296f89/setup.py#L18-L21) brings in `crcmod` unconditionally. This means that users who install `threefive` wind up with `crcmod`.

My request is to make `crcmod` an [optional dependency](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies), i.e. to put it in an `extras_require`. This would allow users to control whether they get it or not.

In that world `pip install threefive` wouldn't bring in `crcmod`, but something like `pip install threefive[decoding]` would.

The same request could be made re: `pyaes`, but it's less pressing in that case because it is a pure Python module that doesn't need to be compiled for exotic architectures.

Thanks for this excellent library!

**Comment by bbayles** [comment]
As an alternative, [pycrc](https://github.com/tpircher/pycrc/) is better maintained than `crcmod` (last release 2021 vs. 2010) and doesn't require an extension module.

I believe this is the equivalent to `threefive`'s use:
```python
from pycrc.algorithms import Crc
from pycrc.models import CrcModels

params = CrcModels().get_params('crc-32-mpeg')
alg = Crc(
    table_idx_width=8,
    **{k: params[k] for k in ('width', 'poly', 'reflect_in', 'xor_in', 'reflect_out', 'xor_out')}
)

bytes_to_encode = b'\x00' * 8
encoded_bytes = alg.table_driven(bytes_to_encode)
```

Hope this is helpful!

**Comment by futzu** [comment]
Sounds reasonable. 
I'll change the setup.py in the next day or so, 
but I am unfamiliar with pycrc, and I need to test it a little first.

**Comment by futzu** [comment]
![image](https://user-images.githubusercontent.com/52701496/154786900-d44fac4a-09b8-45ba-91bf-6738e3720575.png)

Works for me, let me know if that works for you. 

Adrian

**Comment by bbayles** [comment]
Excellent! This solves my problem.

However, I think there's a problem with the implementation. `setup.py` [now has](https://github.com/futzu/scte35-threefive/blob/0a306840a3472e43c4650f01f34551b4c8243a33/setup.py#L18) `extra_requires` as a list, but for optional dependencies you'd want to use `extras_require` as a dict. Example:

```python
    extras_require={
        "all": ["crcmod", "pyaes"],
    },
```

This would allow a user to do `pip install threefive[all]` to get the extra packages.

**Comment by futzu** [comment]
I like it. 
I'll go ahead and make a new release with the "all" as you suggested.

**Comment by futzu** [comment]
If you're good, close this issue please, 
If you're not good, let me know and Ill fix it. 

Thanks for the input man,
 I have been wanting to make this change for a while, 
but I wasn't sure on how to do it in setup.py.


Adrian

**Comment by futzu** [comment]
Because of you, I wrote my own crc32 function and don't use crcmod anymore. 
:)

**Comment by bbayles** [comment]
Great - one less binary dependency,

I think you could make your implementation much faster by computing the table outside the function rather than [inside](https://github.com/futzu/scte35-threefive/blob/ff538f70f331e7eb38f9a65c6f669666a6573095/threefive/crc.py#L35)? Doesn't look like it's cached currently?
