### ISSUE TITLE
'hasp.py' for SCTE-35 HLS parsing throws error "OverflowError: int too big to convert" or "[Errno 104] Connection reset by peer"

### ISSUE THREAD

**Issue by moving-digital** [futzu/threefive#49]
Hi @futzu 

First of all, great project! :)

When using `hasp.py` with the following command: `pypy3 hasp.py <m3u8_manifest>` I keep getting the following errors:

```
OverflowError: int too big to convert 
```
and 
```
[Errno 104] Connection reset by peer
```

I have tried with:
- Few different Live HLS streams from my side, which have been on-air for the past few years, and also the m3u8 manifest from https://github.com/futzu/scte35-threefive/issues/37 renamed to "9syd_master1.m3u8.txt" (to comply with github upload). It does not work and throws the above error
- The 2 m3u8 examples available on your github. It works.

Would you happen to know what could be the issue? I can provide you with the m3u8 manifest that are causing the issue.

**Comment by futzu** [comment]
Are you running the latest version of threefive, 2.3.21? 


try this.
    python3 hasp.py https://phls-vod.cdn.turner.com/cnnngtv/cnn/hls/2018/12/03/urn:ngtv-show:115615/index_1.m3u8

Output looks like 
![image](https://user-images.githubusercontent.com/52701496/155003249-318eb4eb-347f-41e2-aa9d-89a3a1d3e78e.png)


I have to run to Walmart to find me a new girlfriend real quick, but tonight Ill check this out in more detail.


Adrian

**Comment by moving-digital** [comment]
Hi @futzu 

Seems like I'm running 2.3.21 indeed:

![image](https://user-images.githubusercontent.com/81666507/155044296-fc6f44c1-a308-4ffb-8872-43470c3ad529.png)

![image](https://user-images.githubusercontent.com/81666507/155044329-fff38901-9761-44ca-9914-95fa7baff6a5.png)

I'm not based in US and the m3u8 is geoblocked so I am getting 403 Forbidden / Access Denied.

Edit: I used my VPN to download the m3u8 locally, then use it as an offline m3u8 playlist, it works:

![image](https://user-images.githubusercontent.com/81666507/155052913-4483c9ab-d263-4bf1-b02f-d2704e14f840.png)

So it means threefive does not like my HLS/m3u8 playlist... Let me know when you have time to have a look at it :-) I can pass them to you.

Error with Playlist #1:

```
Base Time       : 49074.6608
 HLS Time        : 156.0
 Segment Start   : 49230.6608     Segment Duration  : 4.0
 Cue:

Parsing PacketsTraceback (most recent call last):
  File "hasp.py", line 231, in <module>
    HASP(arg).decode()
  File "hasp.py", line 216, in decode
    self.do_segment(line)
  File "hasp.py", line 197, in do_segment
    self.show_segment_times(stanza)
  File "hasp.py", line 182, in show_segment_times
    stanza.do_cue()
  File "hasp.py", line 120, in do_cue
    tf = threefive.Cue(self.cue)
  File "/usr/local/lib/pypy3.7/dist-packages/threefive/cue.py", line 56, in __init__
    self.bites = self._mk_bits(data)
  File "/usr/local/lib/pypy3.7/dist-packages/threefive/cue.py", line 257, in _mk_bits
    bites = int.to_bytes(i, i_len, byteorder="big")
OverflowError: int too big to convert
```

Error with Playlist #2:

```
 Base Time       : 0.0
 HLS Time        : 1589.554634
 Segment Start   : 1589.554634    Segment Duration  : 6.006


Traceback (most recent call last):
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/pypy3/lib-python/3/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/pypy3/lib-python/3/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/pypy3/lib-python/3/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/pypy3/lib-python/3/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib/pypy3/lib-python/3/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib/pypy3/lib-python/3/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/usr/lib/pypy3/lib-python/3/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/pypy3/lib-python/3/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/pypy3/lib-python/3/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/pypy3/lib_pypy/_cffi_ssl/_stdssl/__init__.py", line 509, in do_handshake
    raise pyssl_error(self, ret)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hasp.py", line 231, in <module>
    HASP(arg).decode()
  File "hasp.py", line 204, in decode
    with threefive.reader(self.m3u8) as self.manifest:
  File "/usr/local/lib/pypy3.7/dist-packages/threefive/reader.py", line 44, in reader
    return urllib.request.urlopen(uri)
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/pypy3/lib-python/3/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

**Comment by futzu** [comment]
Lets stick to hasp.py.
* hasp.py does not use the m3u8 lib.

Errors:
1. I need to see the SCTE-35 Cues in that one. Post it and but change the urls if you want. I dont need the segments, just the m3u8.


2. The connection was reset by the web server, threefive didn't do it. 
     * make sure you play the m3u8 in mplayer, vlc, or ffplay
    * check the cert from the website.
    * Make sure your ssl libs are up to date.
     

Try these m3u8 files
[iframe.m3u8.txt](https://github.com/futzu/scte35-threefive/files/8116487/iframe.m3u8.txt)
[master1.m3u8.txt](https://github.com/futzu/scte35-threefive/files/8116488/master1.m3u8.txt)

_ Easier way to check the version_
![image](https://user-images.githubusercontent.com/52701496/155125290-025ccfdd-a497-40e8-8bf2-fdb53b5341ad.png)

**Comment by moving-digital** [comment]
> Lets stick to hasp.py.
> 
> * hasp.py does not use the m3u8 lib.
> 
> Errors:
> 
> 1. I need to see the SCTE-35 Cues in that one. Post it and but change the urls if you want. I dont need the segments, just the m3u8.

Thanks @futzu  ! Please find the .m3u8 attached. 

[ftv_scte35.m3u8.txt](https://github.com/futzu/scte35-threefive/files/8116534/ftv_scte35.m3u8.txt)

**Comment by moving-digital** [comment]
Hi @futzu 

> Try these m3u8 files [master1.m3u8.txt](https://github.com/futzu/scte35-threefive/files/8116488/master1.m3u8.txt)

It does not work and I'm being thrown the following error message:

```
$ pypy3 hasp.py master1.m3u8
Parsing PacketsTraceback (most recent call last):
  File "hasp.py", line 231, in <module>
    HASP(arg).decode()
  File "hasp.py", line 216, in decode
    self.do_segment(line)
  File "hasp.py", line 193, in do_segment
    stanza.decode()
  File "hasp.py", line 132, in decode
    self._get_pcr_start(self.segment)
  File "hasp.py", line 93, in _get_pcr_start
    self.start = self.pcr = round(pcr_start / 90000.0, 6)
UnboundLocalError: local variable 'pcr_start' referenced before assignment
```

**Comment by futzu** [comment]
[ I updated hasp.py](https://github.com/futzu/scte35-threefive/blob/master/examples/hls/hasp.py)
It should fix the pcr_start issue. 


Adrian

**Comment by moving-digital** [comment]
> OverflowError: int too big to convert

Thanks @futzu !

Keep me posted when you got a fix for "OverflowError: int too big to convert" too 👍  There was so many different ways to handle SCTE-35 in HLS playlist, that I'm sure there are other people out there with the same syntax.. lol

**Comment by moving-digital** [comment]
> [ I updated hasp.py](https://github.com/futzu/scte35-threefive/blob/master/examples/hls/hasp.py) It should fix the pcr_start issue.
> 
> Adrian

Thanks @futzu !

Keep me posted once you got a fix for "OverflowError: int too big to convert" too 👍 

There are so many different ways to handle SCTE-35 in HLS playlist, that I'm sure there are other people out there with the same syntax...

**Comment by futzu** [comment]
* The Overflow Error is not a threefive issue. 
*  Connection reset ny peer Error is also not a threefive issue.
* No, the stuff you showed me does not look like or decode as SCTE-35.

**Comment by futzu** [comment]
I am closing this  issue, 

The pcr_start thing has been fixed.

The overflow error 
**not a threefive issue.** 

The server connection thing, 
**not a threefive issue.** 


You are not using SCTE-35 HLS tags  properly, 
* **There is no SCTE-35 Cue.**
* **The timestamps are not formatted correctly** 
* **The dates are not formatted correctly**
* etc......

The HLS is not so good either.

I'm not being a dick, I'm being honest with you.

This is what I do for a living,

 if you want me to fix it for you 
and show you how to do it,  shoot me an email.
