### ISSUE TITLE
Decode / encode round trip produces unexpected results

### ISSUE THREAD

**Issue by bbayles** [futzu/threefive#71]
Here's something I ran into:
```python
from threefive import Cue

orig = '/DAlAAAAAyiYAP/wFAVNqW2Jf+//WP/YQ/4AUnrYAAEBAQAAGk9JoA=='
orig_cue = Cue(orig)
orig_cue.decode()

new_cue = Cue(orig_cue.encode())
new_cue.decode()

print(orig_cue.get()['info_section']['pts_adjustment_ticks'], new_cue.get()['info_section']['pts_adjustment_ticks'])
```

Different results for the two values: `207000 206999`

---

I think the issue is probably in the `encode` process:
* [`_encode_pts_adjustment`](https://github.com/futzu/scte35-threefive/blob/a5f9496fc66cdc4bbf07a9f8885a95d9dc1c0324/threefive/section.py#L126-L132) uses `nbin.add_90k(self.pts_adjustment, 33)`
* [`add_90k`](https://github.com/futzu/scte35-threefive/blob/a5f9496fc66cdc4bbf07a9f8885a95d9dc1c0324/threefive/bitn.py#L151-L158) uses floating point math instead of integer math.

It looks like `pts_adjustment_ticks` is [still saved as an integer](https://github.com/futzu/scte35-threefive/blob/a5f9496fc66cdc4bbf07a9f8885a95d9dc1c0324/threefive/section.py#L61), so perhaps it could be encoded again directly instead of going through the computed value?

**Comment by futzu** [comment]
Good catch.
You're right, I should be using ticks there.
I'll try to push an update tonight.

You know you can use dot notation, right?

```js

print(cue.info_section.pts_adjustment_ticks, new_cue.info_section.pts_adjustment_ticks)

```

**Comment by futzu** [comment]
* I added this to the __SCTE35Base__ class

```python3
    @staticmethod
    def as_ticks(float_time):
        """
        90k timestamps to ticks
        """
        return  int(round(float_time * 90000))
    
```
* I updated the __SpliceInfoSection__ class  _( I applied similar updates to Splice Commands and Descriptors)_
```python3
    def _encode_pts_adjustment(self, nbin):
        """
        encode SpliceInfoSection.pts_adjustment_ticks
        """
        if not self.pts_adjustment_ticks:
            self.pts_adjustment_ticks = 0
            if self.pts_adjustment:
              self.pts_adjustment_ticks =  as_ticks(self.pts_adjustment) 
        self._chk_var(int, nbin.add_int,"pts_adjustment_ticks", 33) 
```
* then I ran your test.
```js
a@debian:~/build/scte35-threefive$ pypy3
Python 3.8.13 (7.3.9+dfsg-5, Oct 30 2022, 09:55:31)
[PyPy 7.3.9 with GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from threefive import Cue
>>>> orig = '/DAlAAAAAyiYAP/wFAVNqW2Jf+//WP/YQ/4AUnrYAAEBAQAAGk9JoA=='
>>>> orig_cue = Cue(orig)
>>>> orig_cue.decode()
True
>>>> new_cue = Cue(orig_cue.encode())
>>>> new_cue.decode()
True
>>>> print(orig_cue.info_section.pts_adjustment_ticks, new_cue.info_section.pts\
_adjustment_ticks)
207000 207000
```

I'll push a new pip release shortly

**Comment by futzu** [comment]
# pip it up.

## latest is 2.3.63

**Comment by futzu** [comment]
I fixed this before I pushed the release.

```python3
    def _encode_pts_adjustment(self, nbin):
        """
        encode SpliceInfoSection.pts_adjustment_ticks
        """
        if not self.pts_adjustment_ticks:
            self.pts_adjustment_ticks = 0
            if self.pts_adjustment:
              self.pts_adjustment_ticks =  as_ticks(self.pts_adjustment)  #   <--- should have been self.as_ticks
        self._chk_var(int, nbin.add_int,"pts_adjustment_ticks", 33) 
```

**Comment by bbayles** [comment]
Many thanks for the quick action!

Also: release the Super Kabuki script! I will help maintain it, ha.
