### ISSUE TITLE
Having latest.py file breaks rpm build

### ISSUE THREAD

**Issue by NicoAdrian** [futzu/threefive#78]
Hello,

The file `latest.py` in master branch breaks RPM builds, because it tries to compile to python bytecode all the files and `latest.py` is not syntaxically correct:

```
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python3 1
*** Error compiling '/builds/myproject/.venv/lib/python3.6/site-packages/threefive/latest.py'...
  File "/latest.py", line 1
    2.3.75
         ^
SyntaxError: invalid syntax
```

**Comment by futzu** [comment]
Sorry about that 2.3.75 was only up for about six hours before I caught the mistake.
 We sorted that out at #77 .
2.3.79  is working correctly.
```lua
~# pypy3 
Python 3.9.16 (7.3.11+dfsg-2, Feb 06 2023, 16:52:03)
[PyPy 7.3.11 with GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import threefive
>>>> threefive.version
'2.3.79'
```

git pull and let me know if that works for you.

**Comment by futzu** [comment]
Man you caught just at the wrong time latest.py was there for about 30 minutes before I fixed it. I never intentionally leave a repo broken. Sorry about that. 

Are you building rpms because of Pep668, or just for a build? 

If you can, I would love a spec file for threefive,

**Comment by NicoAdrian** [comment]
The file is still there in master unfortunately (https://github.com/futzu/scte35-threefive/blob/master/threefive/latest.py)

**Comment by futzu** [comment]
I am so sorry man, I don't how I missed that again. 
File is gone now.

**Comment by futzu** [comment]
![image](https://user-images.githubusercontent.com/52701496/229931735-ab59f9f2-494e-44b8-80fe-bdc9fba557cb.png)

**Comment by futzu** [comment]
If you good, you can close this, if not talk to me and we'll figure it out.

**Comment by NicoAdrian** [comment]
Yes it's all good now, thanks.
