### ISSUE TITLE
The SCTE35 "section_length" value is always 3 bytes less than the actual size

### ISSUE THREAD

**Issue by ishakhrai** [futzu/threefive#83]
I'm learning SCTE35 staff and I can't figure out one thing. Why is the length of "section_length" always less than 3 bytes from the actual size?
Example:
```
>>> test_raw = "/DAlAAAAAAAAAP/wFAUAAAZ5f+/+AAAAAH4Ae5igAAAAAAAA5nk27g=="
>>> test_cue = Cue(test_raw)
>>> test_cue.decode()
>>> test_cue.show()
```

```
"section_length": 37,

```
But if I will check  len(test_cue.bites) will see 40: 
```
>>> len(test_cue.bites)
40
```
I've already checked the documentation but did not find answer: 
* https://wagtail-prod-storage.s3.amazonaws.com/documents/SCTE_281-1_2023.pdf
* https://wagtail-prod-storage.s3.amazonaws.com/documents/SCTE_281-2_2023.pdf
* https://alexzambelli.com/blog/wp-content/uploads/SCTE-35%20In-Band%20Event%20Signaling%20%28Seattle%20Video%20Tech%20-%20Dec%202018%29.pdf

Probably some "header" that is not included in the "section_length".  From the source of the lib i see that "section_length" calculation like this - # `11 bytes for info section + command + 2 descriptor loop length  + descriptor loop + 4 for crc`, but I`m still confused.

Сould someone please explain why we have this 3 byte difference in "section_length" and the actual size ?

Sorry, the question not related to the project

**Comment by futzu** [comment]
No problem man , that threw me for a while too. 

 `(8 + 1 + 1 + 2 + 12 ) >> 3 = 3 bytes` 

![image](https://user-images.githubusercontent.com/52701496/233795830-7c6acd0f-584a-4b3c-ac15-d698896abde2.png)

__Section Length is the number of bytes immediately following Section Length.__
![image](https://user-images.githubusercontent.com/52701496/233795777-bb06a07b-2ab0-41ad-86d7-b36978a45a34.png)


__Does that make sense?__

**Comment by ishakhrai** [comment]
yep, it is clear now.
@futzu  Thank you very much
