### ISSUE TITLE
cmd.py in latest PyPI release is not syntaxically correct

### ISSUE THREAD

**Issue by NicoAdrian** [futzu/threefive#84]
Hello,

The file `cmd.py` in the latest release in PyPI breaks RPM builds, because it tries to compile to python bytecode all the files and `cmd.py` is not syntaxically correct:

```
*** Error compiling '/builds/myproject/.venv/lib/python3.6/site-packages/threefive/cmd.py'...
  File "/cmd.py", line 1
    /*
    ^
SyntaxError: invalid syntax
```

**Comment by futzu** [comment]
I am so sorry I keep doing this to you, it's not supposed to even be in there.
Man my mom just died, I have been distracted taking care of her the last few months.
My focus should improve soon. I'll do another buildf for you within the hour. 

Again, I apologize. 

Adrian

**Comment by NicoAdrian** [comment]
Really sorry to hear that. Don't worry, it's not urgent at all. I used a previous version an it's all good

**Comment by futzu** [comment]
Thanks man.

It's already done.
pypy3 -mpip install --upgrade threefive 

![image](https://github.com/futzu/scte35-threefive/assets/52701496/80d9b48e-dc2d-499c-809f-dc1b65e8abe6)

**Comment by futzu** [comment]
update: v2.3.91 is now out. I had a weird pts bug that showed up rarely, but was bug none the less. 
Hey man, since you are verifying the builds anyway, you want to give me a hand with things? Maybe you verify the build before pushing it to pip package. It would be a big help having someone else take a look before things get pushed.

**Comment by futzu** [comment]
You good?

**Comment by NicoAdrian** [comment]
Yea it works fine now, thanks.
I can help you if want.
Or maybe juste add something like a GitHub action ? I don't really know how it works but you should be able to run a command like `python -m compileall .` (create a virtualenv before then install the dependencies) and check the return status
