### ISSUE TITLE
decode local ts file fails...

### ISSUE THREAD

**Issue by robclemamzn** [futzu/threefive#89]
getting ''str' object has no attribute 'read'' from threefive    version     2.4.9

when running the posted example code below.

Can you suggest any updates or changes?
```
% cat z.py
"""
Example using Stream.decode() with a custom function
to return a list of cues from a video

Usage:

pypy3 cue_list.py video.ts

"""
import sys
import threefive
from threefive import Stream, Cue

# A list to hold cues 
CUES=[]

def cue_func(cue):
    """
    threefive.Stream.decode cqn be passed in a
    custom function that accepts a Cue as the only arg.
    this is an example of a custom function.

    """
    CUES.append(cue)
    cue.show()


def do():
    """
    do collects a list of Cues  from a Stream
    """
    arg = sys.argv[1]
    strm = Stream(arg)
    strm.decode(func=cue_func) # cue_func is the custom function from above


if __name__ == "__main__":
    do()
    [print(cue.command.name,cue.encode()) for cue in CUES]

```

    
    the output in full reads:
    

```
     python3 z.py /path/index_1_00008.ts

Traceback (most recent call last):
  File "/Users/robclem/scripts/z.py", line 40, in <module>
    do()
  File "/Users/robclem/scripts/z.py", line 36, in do
    strm.decode(func=cue_func) # cue_func is the custom function from above
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robclem/scripts/threefive/stream.py", line 79, in decode
    if not self._find_start():
           ^^^^^^^^^^^^^^^^^^
  File "/Users/robclem/scripts/threefive/stream.py", line 65, in _find_start
    one = self._tsdata.read(1)
          ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'read'

```

**Comment by futzu** [comment]
Works perfectly for me, 

Splice Insert /DAvAAAAAAAA///wFAUAAAASf+/+dcFLSn4AZv8wAAES/wAKAAhDVUVJAAAAEuqoRz8=
Splice Insert /DAvAAAAAAAA///wFAUAAAASf+/+dcFLSn4AZv8wAAES/wAKAAhDVUVJAAAAEuqoRz8=
Splice Insert /DAvAAAAAAAA///wFAUAAAASf+/+dcFLSn4AZv8wAAES/wAKAAhDVUVJAAAAEuqoRz8=
Splice Insert /DAvAAAAAAAA///wFAVAAAT2f+/+eMpEWX4A9zFAAAEL/wAKAAhDVUVJAAAACwRZmfY=
Splice Insert /DAvAAAAAAAA///wFAVAAAT2f+/+eMpEWX4A9zFAAAEL/wAKAAhDVUVJAAAACwRZmfY=
Splice Insert /DAqAAAAAAAA///wDwUAAAASf0/+dihKegABEv8ACgAIQ1VFSQAAABIe1kvb
Splice Insert /DAqAAAAAAAA///wDwUAAAASf0/+dihKegABEv8ACgAIQ1VFSQAAABIe1kvb
Splice Insert /DAqAAAAAAAA///wDwUAAAASf0/+dihKegABEv8ACgAIQ1VFSQAAABIe1kvb
Splice Insert /DAvAAAAAAAA///wFAUAAAAWf+/+eqdoEv4Ag9YAAAoI/wAKAAhDVUVJAAAACEMQGFI=
Splice Insert /DAvAAAAAAAA///wFAUAAAAXf+/+eq+lcv4Ae5igAAEI/wAKAAhDVUVJAAAACEre6z4=
Splice Insert /DAqAAAAAAAA///wDwVAAAT2f0/+ecF1mQABC/8ACgAIQ1VFSQAAAAsuZVlR
Splice Insert /DAqAAAAAAAA///wDwVAAAT2f0/+ecF1mQABC/8ACgAIQ1VFSQAAAAsuZVlR
Splice Insert /DAqAAAAAAAA///wDwUAAAAYf0/+eys+EgABCP8ACgAIQ1VFSQAAAAjUl9qC
Splice Insert /DAvAAAAAAAA///wFAVAAAT3f+/+fidyuX4A9zFAAAEM/wAKAAhDVUVJAAAADPhcyp0=
Splice Insert /DAvAAAAAAAA///wFAVAAAT3f+/+fidyuX4A9zFAAAEM/wAKAAhDVUVJAAAADPhcyp0=
Splice Insert /DAqAAAAAAAA///wDwVAAAT3f0/+fx6j+QABDP8ACgAIQ1VFSQAAAAwz88FN
Splice Insert /DAqAAAAAAAA///wDwVAAAT3f0/+fx6j+QABDP8ACgAIQ1VFSQAAAAwz88FN
Splice Insert /DAqAAAAAAAA///wDwUAABY6f8/+fwxPcwAAAAAACgAIQ1VFSQAAAADXFlx5

I just cut and pasted what you had, I swear.

It's got to be something silly, 

**try this**

`python3 z.py https://futzu.com/xaa.ts`

**Comment by robclemamzn** [comment]
using  python 3.11.5.

i've gotten it running from another machine so it's something stupid on my corporate laptop.  please close this case.

**Comment by futzu** [comment]
let me know what it was if you figure it out. Feel free hit me back.

Adrian
