### ISSUE TITLE
Crash when decoding private descriptors from PrivateCommand 

### ISSUE THREAD

**Issue by casimcdaniels** [futzu/threefive#96]
I'm experiencing an issue when reading SCTE-35 cues from an MPEG-TS stream using this library. The stream in question has periodic `PrivateCommand` SCTE-35 command types, as shown below in the `pcrextract` output. 
```
* pcrextract: PID: 0x0033 (51), SCTE 35 command PrivateCommand
* pcrextract: PID: 0x0033 (51), SCTE 35 command PrivateCommand
* pcrextract: PID: 0x0033 (51), SCTE 35 command PrivateCommand
* pcrextract: PID: 0x0033 (51), SCTE 35 command PrivateCommand
* pcrextract: PID: 0x0033 (51), SCTE 35 command PrivateCommand
* pcrextract: PID: 0x0033 (51), SCTE 35 command SpliceInsert out, exec at PTS 0x1089E9D7D
```

**Observed behavior**

Everytime a PrivateCommand appears in the PID, threefive crashes.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/stream.py", line 234, in decode
    cue = self._parse(pkt)
          ^^^^^^^^^^^^^^^^
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/stream.py", line 486, in _parse
    cue = self._parse_scte35(pkt, pid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/stream.py", line 534, in _parse_scte35
    cue = self._parse_cue(pay, pid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/stream.py", line 511, in _parse_cue
    if cue.decode():
       ^^^^^^^^^^^^
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/cue.py", line 72, in decode
    bites = self._mk_descriptors(bites)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/cue.py", line 165, in _mk_descriptors
    self._descriptor_loop(bites[:dll])
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/cue.py", line 84, in _descriptor_loop
    spliced = splice_descriptor(loop_bites)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cmcdaniels/.pyenv/versions/3.12.1/lib/python3.12/site-packages/threefive/descriptors.py", line 403, in splice_descriptor
    spliced = ( SpliceDescriptor(bites),descriptor_map[tag](bites))[tag in descriptor_map]
                                        ~~~~~~~~~~~~~~^^^^^
KeyError: 68
```

After digging through the code, it seems that the decode logic is expecting a defined value within the descriptor map for the descriptor type, but since  my stream has private descriptors tags an exception occurs on the lookup. The tag is able to be any u32 so it would seem there needs to be support for private descriptors added to this library.

**Comment by futzu** [comment]
There is,  directions are on the README with code example.

![image](https://github.com/futzu/scte35parser-threefive/assets/52701496/6c5d69bd-5687-4b96-bd40-d9ad7d8ea1bc)

![image](https://github.com/futzu/scte35parser-threefive/assets/52701496/1f4d8419-e517-4d07-a449-903863b5d83f)

**Comment by futzu** [comment]
If you need a command , it works the same way. 
I don't throw a lot of errors, and I have considered just passing through as is,
but I don't know. I just tend to give the people what they want. 

If you have a better way to handle it, tell me.   All the best parts of threefive came from other people, seriously.

**Comment by casimcdaniels** [comment]
While I could write a custom implementation to handle, I don't need to actually decode the PrivateCommand signals and their associated splice descriptors. It seems like there could be a private descriptor class to generically represent the occurrence, much like there is for private command. If a user needs to decode more specifically, they can follow your steps.

This has the benefit of not needing to know about all possible signals that the source of content could be producing. Any addition on their end will end up breaking applications built with threefive.

**Comment by futzu** [comment]
spliced = ( SpliceDescriptor(bites),descriptor_map[tag](bites))[tag in descriptor_map]

I don't know if you recognize the syntax, but that is python  short hand operator or whatever it's called, 
it's supposed to call SpliceDescriptor(bites)  if  [tag in descriptor_map] is False.

Can you send me the encoded  Cue string?  It is supposed to work like you expect.

**Comment by futzu** [comment]
```py3
Python 3.8.13 (7.3.9+dfsg-5, Oct 30 2022, 09:55:31)
[PyPy 7.3.9 with GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> a = {1:"yes",2:"no"}
>>>> b =1
>>>> ("NO","YES")[b in a]
'YES'
>>>> 
>>>> b=3
>>>> ("NO","YES")[b in a]
'NO'
>>>> 

```

**Comment by futzu** [comment]
That's how it's supposed to work.

**Comment by futzu** [comment]
you could try  changing the  splice_descriptor function  to something like this
```py3
def splice_descriptor(bites):
    """
    replaced splice_descriptor
    """
    tag = bites[0]
    if tag in descriptor_map:
       spliced = descriptor_map[tag](bites)
   else:
       spliced = SpliceDescriptor(bites)
    spliced.decode()
    return spliced

```

**Comment by futzu** [comment]
I did the change I mentioned above, and fix the return for encode and it works, 
```py3
Python 3.8.13 (7.3.9+dfsg-5, Oct 30 2022, 09:55:31)
[PyPy 7.3.9 with GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from  threefive.descriptors import SpliceDescriptor
>>>> from threefive import Cue, TimeSignal
>>>> cue=Cue()
>>>> cue.command = TimeSignal()
>>>> cue.command.time_specified_flag=True
>>>> cue.command.pts_time=35.35
>>>> sd = SpliceDescriptor()
>>>> sd.tag=112
>>>> sd.identifier="bobo"
>>>> sd.private_data=b"threeblindmice"
>>>> cue.descriptors.append(sd)
>>>> data = cue.encode()
>>>> data
'/DAqAAAAAAAAAP/wBQb+ADCLvAAUcBJib2JvdGhyZWVibGluZG1pY2W3SqqA'
>>>> cue2 = Cue(data)
>>>> cue2.decode()
True
>>>> cue2.show()
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",
        "sap_details": "No Sap Type",
        "section_length": 42,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 0,
        "pts_adjustment": 0.0,
        "cw_index": "0x00",
        "tier": "0x0fff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 20,
        "crc": "0xb74aaa80"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 35.35,
        "pts_time_ticks": 3181500
    },
    "descriptors": [
        {
            "tag": 112,
            "descriptor_length": 18,
            "identifier": "bobo",
            "private_data": [
                116,
                104,
                114,
                101,
                101,
                98,
                108,
                105,
                110,
                100,
                109,
                105,
                99,
                101
            ]
        }
    ]
}
>>>> 
```

I'[ll do a build in the morning and it should work as expected.

**Comment by casimcdaniels** [comment]
Appreciate  the quick change! I tested with your change to `splice_descriptor()` and I am now seeing PrivateCommand SCTE-35s printed out without any exceptions.

**Comment by casimcdaniels** [comment]
What do you think of skipping the private descriptor if its unmapped so it doesn't throw an exception?

**Comment by futzu** [comment]
huh? 
replace descriptors.py with this one and see if it works for you 

https://iodisco.com/descriptors.py

**Comment by futzu** [comment]
I figured out why the shorthand didn't work, the key error from the True condition 
```py3
    spliced = ( SpliceDescriptor(bites), descriptor_map[tag](bites) )  [tag in descriptor_map]
                                                   ^ key error                       
```
I thought that would only be processed if  [tag in descriptor_map] was True.

**Comment by casimcdaniels** [comment]
@futzu I'm testing against a realtime MPEG-TS stream so testing is a little annoying and I'm not sure if there's an easy way to get the base64 encode of the SCTE-35 signal with `tsduck`, but I'm getting variable behavior trying to pipe a multicast stream. I'll report in the AM once I get a good snippet.

Another thing, I had to modify the SCTE_TID for the stream to even be picked up
 https://github.com/futzu/scte35parser-threefive/blob/master/threefive/stream.py#L139C4-L139C27

❌ 
 ```
_SCTE35_TID = b"\xFC0"
```

✅ 
 ```
_SCTE35_TID = b"\xFC"
```

Per the SCTE-35 spec, the table ID should be 0xFC: 

<img width="751" alt="image" src="https://github.com/futzu/scte35parser-threefive/assets/4147943/372078b3-0421-4907-81b4-7823c8a944b6">

**Comment by futzu** [comment]
Dude, I can take bytes , int, hex, base64, bit , whatever .

That's wrong, bu it really shouldn't matter, well , unless you're multi-packet SCTE-35 tables, is that what your doing?

You are bursting my bubble man. 
I can't remember the last time somebody caught a legit bug of mine in threefive, 
much less two in same day. 

Adrian

**Comment by futzu** [comment]
However, I do like that people can follow the code enough to find the bugs.

**Comment by futzu** [comment]
It's wrong, but it has been that for years, It's not multipacket,that prompted the failure, I think you have padding on the front of your payload. The whole point of split_by_idx is to remove padding. Padding the front of your payload is weird, it's legal, but weird. :)

**Comment by futzu** [comment]
pip it up.
2.4.29 should solve your problems, let me know if it doesn't.

**Comment by futzu** [comment]
Going forward, to show me the SCTE-35 packets 
```py3
#!/usr/bin/env python3

import sys
from threefive import Stream

class SupaStream(Stream):

    def _parse_scte35(self,pkt,pid):
        print(pkt)
        super()._parse_scte35(pkt,pid)


if __name__ == '__main__':
    args = sys.argv[1:]
    for arg in args:
        supa = SupaStream(arg)
        supa.decode()
```

```smalltalk

a@slow:~$ python3 supastream.py https://futzu.com/xaa.ts
b'G@\x86\x00\xfc0\x16\x00\x00\x00\x00\x00\x00\x00\xff\xf0\x05\x06\xfe\x00\x05\xdd\x01\x00\x00\xc0\xfc\xe7\x80\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
b'G@\x86\x01\xfc0\x16\x00\x00\x00\x00\x00\x00\x00\xff\xf0\x05\x06\xfe\x00\x07<\xeb\x00\x00\xbf\x8b\x96\x02\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
b'G@\x86\x02\xfc0\x16\x00\x00\x00\x00\x00\x00\x00\xff\xf0\x05\x06\xfe\x00\x08\x9c\xd5\x00\x00e\x07\x16F\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
b'G@\x86\x03\xfc0\x16\x00\x00\x00\x00\x00\x00\x00\xff\xf0\x05\x06\xfe\x00\t\xfc\xc0\x00\x00\x0c\xc0q\x84\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
b'G@\x86\x04\xfc0\x16\x00\x00\x00\x00\x00\x00\x00\xff\xf0\x05\x06\xfe\x00\x0b\\\xaa\x00\x00\x92\x9fId\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
```

**Comment by futzu** [comment]
I resolved your issue quickly , I expected a reply.

**Comment by casimcdaniels** [comment]
Thanks for the fix, just tested from pip install and it no longer crashes.

**Comment by futzu** [comment]
Sorry, I got a little bitchy last week. I had to put my cat Junior down, and I was mad at the world.

**Comment by casimcdaniels** [comment]
@futzu Oh dude, no need to apologize. I'm sorry for your loss. 💟 

What's your favorite picture of Junior?

**Comment by futzu** [comment]
I got a question for you.
I think 
```py3
    spliced = ( SpliceDescriptor(bites), descriptor_map[tag](bites) )  [tag in descriptor_map]
                                                   ^ key error                       
```

failing is a bug in python.  you evaluate tuple[0] for False value, tuple[1] for a True value. 
It's evaluating both when the value is False

<br>

Here's a clearer example:

```py3
>>>> data = {"A":1,"B":2}
>>>> stuff = "C"
>>>> ( print("No") ,print(data[stuff] ))[stuff in data]
No
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'C'
>>>> 
```
I don't thinjk ` prtint(data[stuff])`  should ever be evaluated for a False value, 
you can see there it does the False condition by printing "No" first, and then 
throws a key error trying to evaluate the True condition.
The behavior is as expected with an if statement

```py3
>>>> if stuff in data:
....     print(data[stuff])
.... else:
....     print("NO")
....     
NO
>>>> 


```




Do you see that as a bug?

**Comment by casimcdaniels** [comment]
@futzu So I'm still hitting an issue with my particular stream. I don't know if it's a bug in threefive or in my stream or what, but would you be available to chat for me to show you what I'm seeing? I can also forward the stream to you.

From the debugger, I'm hitting an issue within `descriptors.py` at line 55 when attempting to decode the identifier. In my case, the first 4 bytes are `b'\x01 \xeb\xde'`. Error seen is:

```
{UnicodeDecodeError}'utf-8' codec can't decode byte 0xeb in position 2: invalid continuation byte
```

**Comment by futzu** [comment]
I'm wrong about that  being a bug

that's just a  (tuple)[index]
if even works with lists.

```py3
[0,1][False]
0
[0,1][True]
1
a =10
b=20
[0,1][b>a]
1

```

Weird wild stuff.
