### ISSUE TITLE
Are you for hire in scte35 related jobs?

### ISSUE THREAD

**Issue by barhom** [futzu/threefive#97]
Are you for hire in scte35 related jobs? If not, just delete this issue and sorry for the post.

**Comment by futzu** [comment]
Yes I am. The soonest I can start on something new is the beginning of June though.
a@slow.golf is me.

**Comment by futzu** [comment]
I see you're epg stuff, I have an EPG in javascript and html, that will blow your damn mind. you can load 200,000 listings into it,
and it is smoking fast.

**Comment by futzu** [comment]
I haven't seen any email from you. I'm going to close this email me if you need me a@slow.golf
